### PR TITLE
Fix grid image saving & sampler selection, log to outdir path, display sampler options once

### PR DESCRIPTION
**Pull request by warner-benjamin**
Multiple fixes and small improvements:
- Fix sampler selection so it changes the sampler.
- Fix error saving images when using grid option
- Dream log now saves to outdir path file as stated in help and readme
- Sampler argument help displays list of valid samplers once
- Small consistency changes to argument help strings

### CODE REVIEW

**Review by tildebyte — COMMENTED** [review]
Ideally this should be 4 commits

- fix sampler selection; make list of valid samplers
- fix saving image grid option
- fix log save location
- style changes for arg help strings

**Comment by blessedcoolant** [comment]
> Ideally this should be 4 commits
> 
> * fix sampler selection; make list of valid samplers
> * fix saving image grid option
> * fix log save location
> * style changes for arg help strings

A few of these have already been fixed.

1. I just fixed the sampler issue.
2. I believe @lstein already fixed the  log_path issue.

**Review by lstein — APPROVED** [review]
Tested and is working - thanks for fixing these bugs!

**Comment by tildebyte** [comment]
@warner-benjamin; @blessedcoolant is correct, you need to rebase against current main/HEAD

**Comment by warner-benjamin** [comment]
My apologies, I must have looked at a stale list of PRs when I started this PR.

Merged in main and tested grid image saving, sampler picking, and log creation to be working.

**Comment by lstein** [comment]
I tested. Seemed to be OK. Let me know if I merged incorrectly.

**Comment by lstein** [comment]
@warner-benjamin BTW you've made good contributions. I'd be happy to add you as a collaborator.

**Comment by warner-benjamin** [comment]
@lstein Thanks, would be happy to help out.

**Pull request merged**
