### PR TITLE
Added update dependencies in readme.md

### PR DESCRIPTION
**Pull request by softyoda**
Added the info on how to update conda environment "conda env update --file environment.yaml"

### CODE REVIEW

**Comment by softyoda** [comment]
I may have failed my pulled request, the aim of this pr was to add 
```
You may also update the environment dependencies via this command:

<markdown code balise>
(ldm) ~/stable-diffusion$ conda env update --file environment.yaml
<markdown code balise>
```
at line 520 of the readme.md

**Comment by tildebyte** [comment]
@softyoda; It looks like you're trying to open a PR using the GitHub Editor (which is mostly OK). Please close this one, and try again, but base it on the 'development' branch, instead of 'main'.

That is; from the main page of the repo, click where it says 'main' (just below "< Code >"), and select 'development' from the list. THEN you can edit the README and start a new PR.

Also, note that the marks you're looking for above, where you have

`<markdown code balise>`

should actually be

`\``

**Comment by softyoda** [comment]
I'm trying to found a way to simply edit (like wiki edition) without generating many forks, but yeah, sorry, I'm not used to it for now.

**Comment by tildebyte** [comment]
@softyoda; No worries! Thanks for trying. I'll open a PR with your changes.

**Comment by tildebyte** [comment]
@softyoda; Opened #475 for you

**Pull request closed without merging**
