### PR TITLE
Support full-precision embeddings in half precision inference mode

### PR DESCRIPTION
**Pull request by sajattack**
Cast embeddings down to the correct precision

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Interesting. Does it still work with the same memory footprint as the half precision implementation?

**Comment by sajattack** [comment]
> Interesting. Does it still work with the same memory footprint as the half precision implementation?

Yes, I use this to run inference with custom embeddings on an 8GB GPU, because it is not enough VRAM for full-precision.

**Comment by Oceanswave** [comment]
lg2m. thanks for the fix!

**Comment by morganavr** [comment]
Thanks @sajattack for this PR. Now embeddings.pt finally works on my 8GB VRAM GPU!

**Pull request merged**
