### PR TITLE
Add Embiggen automation to upscale-cut-img2img-stitch and achieve high res without extra VRAM

### PR DESCRIPTION
**Pull request by travco**
Add code to automate the process of taking an init image, upscaling it, cutting it into smaller tiles (of a size that can actually be run on someone's GPU with img2img) with some overlapping areas, running all the tiles through the model to refine details with respect to the prompt, and "stitching" the tiles back together.

If you're familiar with "GoBig" (ala https://github.com/lowfuel/progrock-stable) it's sort of like that, except up to an arbitrarily large size (instead of just 2x), on any sized init image, with overlaps between tiles that are configurable, and some extra logic to re-run any number of the tile sub-sections of the image if for example a small part of a huge run got messed up.

An example of an original and a TBP 2.5x output (3x3 tile grid):

These illustrate both the strengths and problems associated with "Twice Baking a Potato" as the output has detail that couldn't possibly be gotten by upscaling that is directly related to the prompt, but can suffer from "motifs" in areas that are supposed to be low-detail or couldn't be handled without the greater context of the image.

### CODE REVIEW

**Comment by lstein** [comment]
I'm really psyched about this. Thank you for contributing! However, there's been a big refactor between "main" and "development" and your PR won't go in cleanly. Could you change the base of the PR to the "development" branch? Thank you.

**Review by lstein — CHANGES_REQUESTED** [review]
Please base this against the development branch.

**Comment by magnusviri** [comment]
Wow! This is amazing!

**Comment by glonlas** [comment]
Excellent work. Could you please add command samples in the README.md otherwise it will be hard for users to discover your feature and understand how it works. 

Documentation is as much as important as the feature :)

**Comment by blessedcoolant** [comment]
Thank you for the PR. The code seems to be working as expected.

---

## Notes:

**General** 

- I would heavily recommend renaming the feature to something more obvious. TBP is not indicative of what it does and I feel it is important that the naming scheme of a feature should reflect that. I previously suggested that such a feature should be called `highdetail` and I'd suggest the same for this too.
- Use a single `-` for the arguments to make it consistent with everything else. Basically `-tbp_scaling` from `--tbp_scaling` for the dream command.
- I feel this feature needs better documentation. The help commands need to be re-written imo so they are more user friendly.

**Functional**

- I feel we can merge `-tbp_scaling` and `-tbp_buffer` into a single argument. There's a lot of arguments that a user has to give already and this will only keep getting longer as more features are added. So I feel arguments that can be consolidated should be done so. In this case we could do a single argument that takes three values -- `-highdetail <scale> <scale_strength> <buffer>`
- The reason for the above change is because when `-highdetail` performs upscaling, it is defaulting to the upscaling strength to be 0.75 always because it is not set. Adding the scale_strength would allow a user to control that as they now do with the `-U` argument -- which is what this basically is.

Example: `-highdetail 2.5 0.6 0.4`

This is a lot simpler way to do this. And we can set logical assertion values and fallbacks to ensure that this command works in all cases.

- In sync with the above changes `--tbp_rerun_tiles` can be renamed to `-highdetail_tiles`

---

**Issues**

- So far I did not face any consistent issues. There was one OOM but I could not replicate that again. So it might have just been my system maxing out in that case. I've tested it on around 10 prompts and it seems to perform as it should.

---

**Thoughts**

This feature has the same downside as GoBig. In the sense that, because the same prompt is used on all the tiled images, it will end up creating repeated patterns across all the tiles based on that prompt. It might work great in some examples but with organic content where patterns are not abstract, this will fall short.

But overall, it's a fantastic feature to have. Especially now that the scaling is not hard capped to 2x.

**Comment by travco** [comment]
@lstein - Thanks, I hadn't anticipated that branch was on track to supercede main, I'll start on figuring what conflicts there are for dev. Gotta say I was a little miffed when I fast-forwarded up to the current version to see "batches" are no longer a thing (and had to refactor them out of the code for this), I'm sure most people couldn't make much use of them, but I actually do have 24GB of VRAM to slosh about and those were precious seconds saved 😆 

@magnusviri  ❤️ 

@glonlas glonlas - Can do, I was hesitant to just start inserting it into the Readme, I'll put some examples after the ones for upscaling (since, they work together nicely and both are about upping resolution)

@blessedcoolant - Thanks for giving it a long look and consideration. 
I agree with you it's not the best name, I named it that as a joke on "512x512 is potato quality" and this doesn't really make it not a potato, just "better" - also for it's originally intended purpose it's "recooking" the image. I'm not sure I'm as keen on "highdetail" as a name if only because I'd expect a feature named that to increase detail/crispness, be something that works on any generation (as opposed to re-running something back through), and not also drastically increase resolution with weird caveats and considerations.
Would you consider "embiggen" or "biggen" a suitable option and a nod to GoBig? Descriptive, but also (to me) humorous and doesn't imply it's going to seamlessly _just work™_.

I'll merge the args, I originally wrote this for an earlier version that wasn't following that stylization on anything. Though I'd put buffer before strength, because that strength argument only affects the strength of ESRGAN that it runs prior to cutting, and from experience it shouldn't do more. It's not a good effect to have semi-transparent tiles (with often shifted/newly created details) overlaid on an upscaled image. Trippy, but not widely useful.

I don't think it should produce any OOM condition, and I haven't observed any increase in VRAM over just img2img, it's basically a complicated wrapper automating img2img runs and almost all of the temporary data it creates in memory during runtime is going to be on main memory RAM, not VRAM.

**Comment by blessedcoolant** [comment]
> Would you consider "embiggen" or "biggen" a suitable option and a nod to GoBig? Descriptive, but also (to me) humorous and doesn't imply it's going to seamlessly just work™.

I like `embiggen`. It's a nice nod to both GoBig and also Ms Marvel. And this is a pretty marvelous feature.

> Though I'd put buffer before strength, because that strength argument only affects the strength of ESRGAN 

That's actually why the reason I suggested it to be second. Because that way it remains in parity with the `-U` command which takes the strength to be second. And it is also descriptive of the order in which the actions take place -- first enlarged with the scale, then how the enlargement is applied using the strength factor and then the embiggen related settings -- which in this case is the buffer.

`I don't think it should produce any OOM condition, and I haven't observed any increase in VRAM over just img2img, it's basically a complicated wrapper automating img2img runs and almost all of the temporary data it creates in memory during runtime is going to be on main memory RAM, not VRAM.`

Yeah. It was mostly a one off thing on my end. I've tried to repro it but I cannot.

**Comment by lstein** [comment]
I just now moved your PR form main to development to avoid any inadverent pulls. However, since you had large changes to simplet2i.py, which is deprecated, this can't be pulled in cleanly.

I wonder if you could move your TBP code into a new module under ldm/dream, and call it from within ldm/generate.py? This would be cleanest.

**Comment by lstein** [comment]
> @lstein - Thanks, I hadn't anticipated that branch was on track to supercede main, I'll start on figuring what conflicts there are for dev. Gotta say I was a little miffed when I fast-forwarded up to the current version to see "batches" are no longer a thing (and had to refactor them out of the code for this), I'm sure most people couldn't make much use of them, but I actually do have 24GB of VRAM to slosh about and those were precious seconds saved laughing

I'm so sorry! Last week we had a poll of users about whether they wanted to keep batches, and the overwhelming response was no. Batches were creating a lot of confusing code, and at that point it wasn't clear how to recover the seeds of images produced by batches. (One of our goals is to enable image reproducibility) It's still not clear to me how  you might recover the seeds for the second or third image in a batch.

**Comment by blessedcoolant** [comment]
Tried out the new changes. Working great. I think the functionality is good to go. I'm gonna do some more extensive testing and then approve this PR.

I would simplify and formalize the documentation a bit. Maybe even move it to its own file so it can be explained in detail. It's not straight forward for someone who is unfamiliar to the idea. But I can do that.  Maybe once I finish the testing, I can make a small push with updated docs.

**Comment by travco** [comment]
Good suggestions, did all but heavy simplification and separation of the Readme entry out into another doc (if you want to take a go at it, feel free). Moved it into a draft state last night because I don't trust my ability to write code or English in the middle of the night well enough 😄 .

No worries lstein, I fully understand why the functionality was dropped. I think I saw another fork "solve" the reproducibility issue by just deciding to "not figure it out" and just iterate +1 on the seed prior to initiating each entry of the batch. Still makes their code pretty rough, returning 2d arrays of images that are also themselves technically 2d arrays - what could possibly go wrong? 😆 

Also finally checked off the long standing "TODO" of making the way `embiggen_tiles` replaces tiles smarter, by doing look-aheads to see if there is another tile to it's right or below that is _going to be replaced_ and adjusting the alpha mask layer it uses accordingly. Irritating code to write, but now connected tiles of an image that are replaced should be replaced in-full instead of having fuzzy transparent gaps between most of them.

**Comment by blessedcoolant** [comment]
Did some testing. Here's some notes.

 The initial image load print message is being logged twice when using Embiggen. Probably once from your script and once from generate. Can you check if this the case? And if so, please fix that up. 

    loaded input image of size 512x768 from outputs/000002.2039293205.png

If it's not from your PR, let me know. I'll have a look at other commits. 

> Good suggestions, did all but heavy simplification and separation of the Readme entry out into another doc 

Don't worry about the docs for now. What you have is good enough. I'm reworking the entire doc structure anyway. When that is live, I'll rewrite/reformat the docs pertaining to embiggen too.

Rest of it seems fine. Once you double check on the log message, I'll approve this PR.

Great job on the feature. Good stuff.

**Comment by travco** [comment]
Yep, spot on, think I left it in there at some point when I was still figuring out if I was going to completely redirect code flow in generate or make a generator.

**Review by blessedcoolant — APPROVED** [review]
Good to go. Thank you for all you work on this.

@lstein Maybe there's still time for it to make the next release.

**Comment by blessedcoolant** [comment]
Off-topic: While reviewing this I realized that having a feature that lets you use the last created image, maybe `-I -1` like we do with seed `-S -1` would be a great way to keep iterating on changes. This would also be especially handy when iterating on img2img changes in general.

We should look into adding.

**Comment by lstein** [comment]
> Off-topic: While reviewing this I realized that having a feature that lets you use the last created image, maybe `-I -1` like we do with seed `-S -1` would be a great way to keep iterating on changes. This would also be especially handy when iterating on img2img changes in general.
> 
> We should look into adding.

I sneakily added that feature yesterday and annoyingly forgot to document it!

**Comment by blessedcoolant** [comment]
> > Off-topic: While reviewing this I realized that having a feature that lets you use the last created image, maybe `-I -1` like we do with seed `-S -1` would be a great way to keep iterating on changes. This would also be especially handy when iterating on img2img changes in general.
> > We should look into adding.
> 
> I sneakily added that feature yesterday and annoyingly forgot to document it!

I noticed. :D Good job.

**Comment by lstein** [comment]
@travco heads up that I extracted all the embiggen documentation from README.md and will be adding it back (along with a pointer) into docs/features/EMBIGGEN.md. Just doing a little testing on my system first.

**Comment by lstein** [comment]
This really works well. I am impressed. I feel bad now that this didn't get into today's release, but I just had too much on my plate juggling optimization versions.

**Review by lstein — APPROVED** [review]
Nice! I will be adding back the embiggen documentation in the next commit.

**Review by lstein — COMMENTED** [review]
Works as advertised. Great job!

**Comment by 0t0m0** [comment]
Hello, 
should this function already work in the development branch?
I have tried to use the function, but unfortunately I always get an error message: 
`raise NotImplementedError("get_noise() must be implemented in a descendent class")`

Maybe I missed something? 

```
dream> a photo of a forest at sunset -s 50 -W 512 -H 512 -I outputs/img-samples/000096.3672131286.png -f 0.4 -embiggen 2.5
<redact>/stable-diffusion/ldm/modules/embedding_manager.py:153: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
>> loaded input image of size 512x512 from outputs/img-samples/000096.3672131286.png
>> ESRGAN upscaling init image prior to cutting with Embiggen with strength 0.75
>> Real-ESRGAN Upscaling seed:None : scale:4x
	Tile 1/4
	Tile 2/4
	Tile 3/4
	Tile 4/4
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<redact>/stable-diffusion/ldm/generate.py", line 329, in prompt2image
    results = generator.generate(
  File "<redact>/stable-diffusion/ldm/dream/generator/base.py", line 67, in generate
    x_T = self.get_noise(width,height)
  File "<redact>stable-diffusion/ldm/dream/generator/base.py", line 116, in get_noise
    raise NotImplementedError("get_noise() must be implemented in a descendent class")
NotImplementedError: get_noise() must be implemented in a descendent class

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 50.88s
Outputs:
```

- Apple M1 16" MBP 32 GB
- OS: macOS
- Python: miniconda (Python 3.10.5)
- Branch: development

**Comment by travco** [comment]
Yep *should* be working on dev, except none of us have a MBP to hit that code path 😅 . Should be as simple as copying the get_noise function from the bottom of the img2img generator over to the embiggen generator. If nobody beats me to it I'll make a PR when I can (~10 hours from now)

**Comment by travco** [comment]
Opened PR for the missing code that should fix it in #553 @0t0m0 , sorry I didn't catch that the first time around.

**Comment by 0t0m0** [comment]
Hi @travco, thanks for your work. 
I tried this version, unfortunately it fails now with this error message: 
`call to get_noise() when init_latent not set`

My programming skills are unfortunately not sufficient to help more, but if there is anything else I can try or test please just let me know.

```
dream> a photo of a forest at sunset -s 50 -W 512 -H 512 -I <redact>/stable-diffusion/outputs/img-samples/000102.50.png -f 0.4 -embiggen 2.5
<redact>/stable-diffusion/ldm/modules/embedding_manager.py:153: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484612588/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
>> loaded input image of size 512x512 from <redact>/stable-diffusion/outputs/img-samples/000102.50.png
>> ESRGAN upscaling init image prior to cutting with Embiggen with strength 0.75
>> Real-ESRGAN Upscaling seed:None : scale:4x
	Tile 1/4
	Tile 2/4
	Tile 3/4
	Tile 4/4
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]
call to get_noise() when init_latent not set
```

**Comment by travco** [comment]
@0t0m0 Thanks, flying a little blind here since I can't test it.

Updated the PR to use the get_noise from txt2img instead. Frankly it probably can be just stubbed as a function since embiggen itself doesn't need noise generated and pushed to the device, it calls img2img which then does it, but since get_noise is expected to return a tensor I didn't want to return a null.

**Comment by daviddrummond95** [comment]
I tested your new approach for Apple Silicon and it works.  Thank you for that fix! This feature is awesome!!!

**Comment by 0t0m0** [comment]
It works :)
Thanks for your work 🙏, a wonderful feature.

**Comment by pigubaoza** [comment]
Hi team, would be useful if we moved the checks to before running ESRGAN upscale, as ESRGAN takes some time to run, and the user is only notified after it is run. 
ie I think we should move line 129-152 to line 98
```
if embiggen[2] < 1:
...
assert emb_tiles_x > 1 or emb_tiles_y > 1 
```

**Pull request merged**
