### PR TITLE
Update attention.py for 16-32GB M1 performance

### PR DESCRIPTION
**Pull request by Any-Winter-4079**
This version should be on par with the fastest ever from 8 to 128 GB. It also allows to generate large images, as before.
Added optimisations for 16-32GB and cleaned up a bit of code.

It would be great to have a tester with CUDA to make sure everything still works.

### CODE REVIEW

**Comment by lstein** [comment]
> This version should be on par with the fastest ever from 8 to 128 GB. It also allows to generate large images, as before. Added optimisations for 16-32GB and cleaned up a bit of code.
> 
> It would be great to have a tester with CUDA to make sure everything still works.

Sure. Testing on CUDA now.

**Review by lstein — APPROVED** [review]
Thanks.

**Comment by i3oc9i** [comment]
I have tested 512x512, 896x576, and 1024x1024 on M1(128G) performance is not degraded w.r.t. 1.4.1 release

**Comment by Vrk3ds** [comment]
tested on mac studio with m1 max 64gb 
512x512, 1.14s/it
768x768 2.32s/it
1024x1024 5.46s/it

tested on MBA M2 16gb
512x512 1.64s/it
768x768 10.23s/it
1024x1024 32.51s/it

Great Work!

**Comment by Birch-san** [comment]
thanks for getting this over the line!  
I've tried applying the same changes on my own fork:  
https://github.com/Birch-san/stable-diffusion/commit/27e645af1aa45d46ab7a984ed77e9f238efd6fcb

on M1 Max (64GB), I'm finding that there's no difference in performance compared to original CompVis code.  
it still takes 10.4s to do an 8-step inference of a 512x512 image, just like CompVis did.

2-sample inference still crashes due to tensor size in einsum, just like CompVis did.

3-sample inference takes 30.1secs, ~3.60s/it. same ballpark as CompVis, which took 30.0secs.

all-in-all: no big difference when running on 64GB. perhaps the 16GB or 32GB users benefit more.

for my fork, I think I won't incorporate the change. since keeping the algorithm simple and aligned with CompVis makes it easy for me to experiment with other changes to the attention algorithm.

**Comment by willcohen** [comment]
This is lovely! Obviously not nearly as speedy as the Max and Ultra above, but the M2 Air 24GB is getting ~4.5-5 it/s with an 832x512 while the GPU is performing some other stuff in the background (video calls all day today!)

**Comment by Vrk3ds** [comment]
@Any-Winter-4079 I noticed that if I enable the web UI the upscaling and face resto isn't showing up anymore? Is that functionality not in this PR?

**Comment by lstein** [comment]
The default install location for GFPGAN has changed. It is now automagically built in src as part of environment.yaml.

**Comment by Vrk3ds** [comment]
@Any-Winter-4079 ok so where do I need to move those directories now?

**Comment by lstein** [comment]
If you run conda env update -f environment-mac.yaml, it should build the GFPGAN directory under src. You will need to copy the GFPGAN model file into src/gfpgan/experiments/pretrained_models/GFPGANv1.3.pth . 

Lincoln

**Comment by Vrk3ds** [comment]
Thank You!

**Comment by Vargol** [comment]
@lstein, @Any-Winter-4079   Not sure how this slipped in but this has really screwed performance on the 8Gb M1

I think this line is a little optimistic

`      if self.mem_total >= 8 and q.shape[1] <= 4096:
`
and probably needs to be

`      if self.mem_total > 8 and q.shape[1] <= 4096:
`

**Comment by Any-Winter-4079** [comment]
> 

Absolutely!

**Comment by Vargol** [comment]
I'll try to but no promises , work will get in the way for another 5 hours or so.

**Pull request merged**
