### PR TITLE
Prompt weighting for creative blending

### PR DESCRIPTION
**Pull request by xraxra**
could probably be improved, but I think this is pretty useful for mixing styles or putting more emphasis on certain things. 

example: `"a forest under blue sky: by Studio Ghibli:1.7 in the style of Starry Night:1"`
        the above example turns into 3 sub-prompts:
        "a forest under blue sky" 1.0 (default if no value)
        "by Studio Ghibli" 1.7
        "in the style of Starry Night" 1.0
        The weights are added and normalized by default, but if `-x` is added, normalization is skipped which allows greater control
        The resulting image will be: 27% a forest under blue sky, 45% by Studio Ghibli, 27% in the style of Starry Night

### CODE REVIEW

**Comment by bmaltais** [comment]
WOW! This sound like you brought one of the best Midjourney prompt feature to StableDiffusion! Great work!

**Comment by bmaltais** [comment]
I applied the change to the latest commit and I get garbled results with -x:

image

Also, the slightest change in prompt weights totally change the picture... compared to Mudjourney that will retain the general look and slightly modify the result based on adjusted weights... almost acting like a new seed.

**Comment by lstein** [comment]
Thanks for the pull request! I'll give it a whirl and merge it in after it checks out.

**Comment by bmaltais** [comment]
The more I play with the weights the more I understang how to use them. Essentially they are super usefull to tweak images. For example, to make it a little more demonic just use: demonic look:0.025

And this will ever so slightly give the image a more sombre look... something you can't do without this feature. A must have.

**Comment by bmaltais** [comment]
Post about you I used this pull request to tweak an image as a demo: https://www.reddit.com/r/StableDiffusion/comments/wvb7q7/using_prompt_weights_to_tweak_an_image_with/

**Comment by lstein** [comment]
I just played around with this myself, using the weights to adjust the different proportions of a hybrid "tabby cat" and "white duck". It works great! Thanks for this.

**Comment by xraxra** [comment]
> I applied the change to the latest commit and I get garbled results with -x:

yeah, using -x doesn't normalize the weights (normalization ensures all values add up to 1.0)
Without normalization, the further over 1.0 you go, the more the image will get distorted. So it is on you to make sure the total values add up to around 1.0 when using -x

It's safe to add small amounts though using -x  (which it sounds like you discovered)

You can also subtract weights by making the values negative, :-0.1  etc

Thanks for merging this! 
There may still be a better way of blending... I need to experiment more with the code.

**Pull request merged**
