### PR TITLE
Fix merging embeddings

### PR DESCRIPTION
**Pull request by david-ford**
Fixed merging embeddings based on the changes made in textual inversion. Tested and working. Inverted their logic to prioritize Stable Diffusion implementation over alternatives, but left the option for alternatives to still be used.

### CODE REVIEW

**Review by lstein — APPROVED** [review]
I spot no problems with the code, and I'll take it on trust that the modifications are doing what they're supposed to since I haven't taken advantage of the training features myself (yet).

**Comment by hopibel** [comment]
The change to ddconfig.resolution (512->256) doesn't match the current value used in the textual inversion repo. The commit there that set it to 512 is older than this PR. Unintentional revert?

**Comment by david-ford** [comment]
> The change to ddconfig.resolution (512->256) doesn't match the current value used in the textual inversion repo. The commit there that set it to 512 is older than this PR. Unintentional revert?

Intentional, decided to go with the lower to support people with less memory to work with. This was before I heard about neons optimizedSD which provides much better performance benefits.

**Comment by lstein** [comment]
This sounds like an inadvertent revert. Could you send me the information
on the two commits you are referring to?

Lincoln

**Pull request merged**
