### PR TITLE
FEAT:  Add ability use all k_* samplers

### PR DESCRIPTION
**Pull request by tildebyte**
Signed-off-by: Ben Alkov <ben.alkov@gmail.com>

"a kitten  -s250 -C12.0 -S560119332"

k_heun:

k_euler (sorry, different seed - 2856290759):

k_dpm_2_ancestral:

### CODE REVIEW

**Comment by tildebyte** [comment]
I feel like we should add the sampler used to the PNG metadata, but I need a break 😁

**Comment by lstein** [comment]
This is great. I'll review and probably merge tomorrow sometime.

**Comment by lstein** [comment]
I've merged this into main, and added the sampler to the metadata stored in the PNG file. I've looked carefully at the images generated with various samplers, and the differences are subtle at best. Is there a combinaton of step and scale that will magnify the differences.

**Comment by tildebyte** [comment]
Rather than try to summarize other's detailed work...

- [Stable Diffusion Sampler Studies](https://docs.google.com/spreadsheets/d/1LBsL0GcCTudXx8X0LjnD-ja6udyq-RMXBFuJG9fSvpA/view) Google Sheet
- [one_squirrel_eight_samplers_eight_cfg_scales](https://www.reddit.com/r/StableDiffusion/comments/wsgcxz/one_squirrel_eight_samplers_eight_cfg_scales/) from Reddit

**Pull request merged**
