### PR TITLE
Clear cuda cache after each image

### PR DESCRIPTION
**Pull request by Oceanswave**
Small change to clear the CUDA cache after generation and processing of each image. Memory Utilization seems to be improved with a negligible effect on performance. Metrics captured in issue #112

### CODE REVIEW

**Comment by smoke2007** [comment]
I just added your 2 lines to test with my 3060 ti 8GB and it ran once and OOM'd on the second one

for a -W512 -H704

Tried to allocate 968.00 MiB (GPU 0; 8.00 GiB total capacity; 5.69 GiB already allocated; 0 bytes free; 6.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Are you sure your system has an adequate NVIDIA GPU?

**Comment by Oceanswave** [comment]
Thanks for the data.

**Comment by smoke2007** [comment]
also to make absolutely sure I did it right, i added a print("emptying cache") , and it does get triggered ;)
With 512 x 512, it does seem to hold, for atleast -n15 that I tried, so for 704, i may just be above a certain treshold/margin where it only works once and doesn't clear up enough for a second go.

**Comment by Oceanswave** [comment]
Thanks a bunch - yeah, Will look into if there's a way we can get back to the initial state some more

**Comment by smoke2007** [comment]
Ok , it seems to work a little with txt2img at 704 dimension, it OOM'd after the third one, for img2img at 704 dimension, it OOM'd after the first one.

**Comment by Oceanswave** [comment]
@smoke2007 if you're still around, could you also try adding torch.cuda.ipc_collect() after the empty_cache() line?

**Comment by smoke2007** [comment]
> @smoke2007 if you're still around, could you also try adding torch.cuda.ipc_collect() after the empty_cache() line?

afraid i'm still only getting one at H704 and OOM on the second

**Comment by smoke2007** [comment]
Ok I went totally nuts and everywhere in simple2ti.py where I saw something done with the model, I added torch.cuda.empty_cache() after it (like in 12 places ;p) and it works now ...., unless it's a coincidence

**Comment by Oceanswave** [comment]
well that's super interesting!

**Comment by lstein** [comment]
A couple of questions, @smoke2007 

1. Have you done any timings before and after the clear_cache() calls. I don't really know CUDA, but I've got to think that the cache is useful for optimizing execution speed.
2. How much of the OOM errors are related to the new GFPGAN code, or is this a problem when you run without --gfpgan?

**Comment by smoke2007** [comment]
I haven't really done timings as it's not that much about speed for me, but being able to just set a batch of 20 and check in a bit later, but now I have to manually rerun the command for each run.

it's definitely all to do with GFPGAN being inefficiently cleared in some kind of manner, once I remove the -G1 parameter, everything continues to run for the amount of -n I specified. 

Especially with img2img the OOM is very consistent, txt2img appears to be able to sometimes run a few more before OOM occurs, but never more than 2 or 3.

**Comment by lstein** [comment]
Benchmarking suggests that @blessedcoolant 's version reduces the OOM errors without the need for aggressive cache clearing, so I will not merge this at this point.

**Pull request closed without merging**
