### PR TITLE
Add link to the model for M1's instruction

### PR DESCRIPTION
**Pull request by erickhun**

### CODE REVIEW

**Comment by i3oc9i** [comment]
In the https://huggingface.co/CompVis/stable-diffusion-v-1-4-original page we can dwonload two 

- sd-v1-4.ckpt
- sd-v1-4-full-ema.ckpt

which is the difference between them ?

**Comment by lstein** [comment]
Do you mind closing and pulling to branch "development" instead? I'm starting to consolidate the day's worth of PRs into the development branch and doing one nightly merge into main after all check sout.

Thanks.

**Comment by lstein** [comment]
> In the https://huggingface.co/CompVis/stable-diffusion-v-1-4-original page we can dwonload two chekpoints
> 
> * sd-v1-4.ckpt
> * sd-v1-4-full-ema.ckpt
> 
> which is the difference between them ?

My understanding is that the non-EMA version of the weights gives more priority to images learned towards the end of its training session, whereas the EMA version equalizes the weights of early and late images. Some people say that the EMA version gives better results, but I haven't seen a good head-to-head comparison. The EMA version is larger.

**Comment by bakkot** [comment]
> Do you mind closing and pulling to branch "development" instead? 

You or the submitter can click the "edit" button to the right of the PR name and change the target branch; no need to close this PR and open a new one.

**Comment by erickhun** [comment]
@lstein changed the branched to be merged in, and adapted the changes

**Review by magnusviri — APPROVED** [review]
Looks good.

**Review by lstein — APPROVED** [review]
LGTM

**Pull request merged**
