### PR TITLE
Add Variations to WebUI

### PR DESCRIPTION
**Pull request by WebDev9000**
This adds variation_amount and with_variations to the web UI.

### CODE REVIEW

**Comment by WebDev9000** [comment]
I've also added the ability to recreate variations via image clicking, I was going to save this for another PR but found time.  Should be ready to review.

**Review by lstein — CHANGES_REQUESTED** [review]
Thanks so much for this. I just tested and noticed that when clicking on a generated image it no longer populates the seed field,  but does populate the new "with variations" field. Can the behavior of setting the seed field be restored?

**Comment by WebDev9000** [comment]
> Thanks so much for this. I just tested and noticed that when clicking on a generated image it no longer populates the seed field, but does populate the new "with variations" field. Can the behavior of setting the seed field be restored?

Please correct me if I am mistaken, but I believe the current behavior is correct - although a little convoluted to explain.  In short, any image generated from just a seed ought to correctly restore the seed when clicked.  Clicking any image will populate the settings needed to reproduce that image.

Let's say you generate 3 new images without any variations:
ss1

Clicking any of the three images will populate the seed field as expected, in this case, clicking the far right one populates with seed 1037781578, as seen in the screenshot.

Now let's say you generate 3 variations off that image by setting the variation amount to 0.05:
ss2

The first two look pretty samey (very low strength variation) but the 3rd one is a nice change, so we click that,.  Here's where the change comes in: The seed for this far left generation is 1756835990. However using that seed won't get you the same image back again.  To get this image, you need to use the original seed of the far right image (1037781578), which is stored as config.seed. Then you need to set the new seed (simply "seed") as the variation seed, 1756835990, and finally add config.variation_amount to the seed in order to get the amount multiplied or traveled, in this case 0.05. (also resetting the UI to zero, otherwise you simply generate more variations)

This will also work for variations of variations, correctly setting the values to what is needed to actually obtain a regeneration of the clicked image.  My goal was restoring the settings that actually generated the image, to easily tweak the parameters for new generations.

**Comment by WebDev9000** [comment]
I should mention that if you would prefer the old behavior, a quick and easy way should be to either revert the last two commits (ff2c4b9, ebeb556), or cherry-pick the first two commits alone (02a6018, c012929).

This will give you the new variations fields without changing the click/seed behavior, which might be helpful for comparison.  Of course, I also don't mind updating the PR if that's what you'd prefer.  Just let me know.

**Comment by WebDev9000** [comment]
@lstein I think you may have mistakenly edited my above description rather than quoting it.  No big deal, just FYI. 😄

**Comment by lstein** [comment]
> @lstein I think you may have mistakenly edited my above description rather than quoting it. No big deal, just FYI. smile

Oh, phooey. Sorry. Is there a way you can restore it?

**Review by lstein — APPROVED** [review]
This is a valuable contribution. Thanks for taking it on.

**Comment by lstein** [comment]
This was merged on the command line.

**Pull request closed without merging**
