### PR TITLE
macOS CI workflow, dream.py exits with an error, but the workflow com…

### PR DESCRIPTION
**Pull request by magnusviri**
…pletes.

### CODE REVIEW

**Comment by magnusviri** [comment]
It runs! The workflow uses the prompts file at tests/prompts.txt. It requires a project secret SD_V1_4_URL, which is a url to the sd cache file (that doesn't require authenticating, which is why it's a secret url). The first time it runs it will take at least an hour to download the sd and huggingface model files. Those files are cached. The cache will is deleted after a week if not used. Once they are cached the run takes about 11 minutes. Once we nail down the environments and all of that we can cache that also. I've got the code in there to do that, it's just commented out.

I created a [pull request](https://github.com/lstein/stable-diffusion/pull/394) for a workflow that only creates the caches. To run that, you click a the button on the Actions tab. You may want to merge that one an hour before you merge this one.

This workflow runs when anything is pushed or a pull request is sent to the main branch. I don't know how other projects manage the triggers. I'm not something I've studied. I'm sure there is a better way to do this. We might want to remove the pull request trigger on main, idk. We should probably add push and pull requests to the development branch.

There are limits to this. I just went and [looked them up](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions). I have consumed tons of minutes testing this, bit I just checked my usage and it says I haven't used any minutes. I'm pretty sure that because this is all public, it's all free. So I guess no limits.

This is from the [run on my repo](https://github.com/magnusviri/stable-diffusion/actions/runs/2997282240). It used the cpu. Here's the stdout of dream.py.

```
* Initializing, be patient...

>> cuda not available, using device cpu
>> Loading model from models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Setting Sampler to k_lms
>> model loaded in 34.07s
#test trending on artstation -s 1 -S 1
 DEBUG: seed at make_image() invocation time =1
>> Are you sure your system has an adequate NVIDIA GPU?
>> Usage stats:
>>   0 image(s) generated in 0.27s
>>   Max VRAM used for this generation: 0.00G
Outputs:

goodbye!
```

Here's the stderr. I'm not sure what the error is about. Maybe it's because there is no GPU?...

```
Generating:   0%|          | 0/1 [00:00<?, ?it/s]
Generating:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/simplet2i.py", line 382, in prompt2image
    image = make_image(x_T)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/simplet2i.py", line 472, in make_image
    uc, c = self._get_uc_and_c(prompt, skip_normalize)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/simplet2i.py", line 549, in _get_uc_and_c
    uc = self.model.get_learned_conditioning([''])
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/models/diffusion/ddpm.py", line 828, in get_learned_conditioning
    c = self.cond_stage_model.encode(
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/modules/encoders/modules.py", line 455, in encode
    return self(text, **kwargs)
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/modules/encoders/modules.py", line 450, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/modules/encoders/modules.py", line 420, in transformer_forward
    return self.text_model(
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/modules/encoders/modules.py", line 393, in text_encoder_forward
    last_hidden_state = self.encoder(
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/runner/work/stable-diffusion/stable-diffusion/ldm/modules/encoders/modules.py", line 320, in encoder_forward
    layer_outputs = encoder_layer(
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 320, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/usr/local/miniconda/envs/ldm/lib/python3.9/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by magnusviri** [comment]
I should add one thing. The prompts are located in tests/prompts.txt because that way anyone can change the type of tests that are done without having to tweak with the workflow file. We can basically put a line in there for every type of test. We should probably specify the seed for each one to make sure the results are consistent. The results are made available to download after the run completes. We can also put images in tests and test img2img, variations, inpainting, or whatever else we want, just as long as it can be done from `dream.py --from_file tests/prompts.txt`

If we wanted to get fancy, we could put the results that should come out of the test and modify the workflow to make sure the files are the same and fail if they aren't.

**Comment by lstein** [comment]
> It runs! The workflow uses the prompts file at tests/prompts.txt. It requires a project secret SD_V1_4_URL, which is a url to the sd cache file (that doesn't require authenticating, which is why it's a secret url). The first time it runs it will take at least an hour to download the sd and huggingface model files. Those files are cached. The cache is deleted after a week if not used. Once they are cached the run takes about 11 minutes. Once we nail down the environments and all of that we can cache that also. I've got the code in there to do that, it's just commented out.
> 
> I created a [pull request](https://github.com/lstein/stable-diffusion/pull/394) for a workflow that only creates the caches. To run that, you click a the button on the Actions tab. You may want to merge that one an hour before you merge this one.

This is looking good. I'll review tomorrow.

**Comment by tildebyte** [comment]
Ye gods, at a glance this is first-class work; **very** nice.

AFA when to run...

- Workflows can trigger on PR 'open' events; that's probably not a good idea - things can still be pretty woolly when a PR is first opened
- Workflows can trigger on 'push' to PR events - also probably not a good idea
- Workflows can trigger when a PR is 'closed' AND merge to target succeeds

```yaml
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```

- IMO, we should trigger on "PR merge to development" (i.e. add 'development' to 'branches' in the previous example), and have a 'tests/dev-prompts.txt' with a *single* prompt, so that we can have an automated smoke test on merge to dev (early warning system :D)

@magnusviri; I'd really like to see a recent Ubuntu added to the matrix and taken for a test drive; if there's a cataclysmic failure, take it out and open an issue to look into adding it later. Windows 10 will need to be special-cased due to file system structure (e.g. at a **minimum**, there's no '/usr').

**Review by lstein — APPROVED** [review]
Very nice! Thanks for doing this.

**Pull request merged**
