### PR TITLE
Remove print statement styling

### PR DESCRIPTION
**Pull request by blessedcoolant**
One of the recent PR's added some styling to some of the print statements which is not recommended. People may have their own custom styling on their terminals which this should not override but it does at the moment.

### CODE REVIEW

**Review by lstein — COMMENTED** [review]
I rather liked the styling. Is this a documented no-no?

**Comment by blessedcoolant** [comment]
> I rather liked the styling. Is this a documented no-no?

I don't think there's any strong rules against it anywhere but I feel like we shouldn't be overriding the users console colors unless there is a strong reason to do so.

In this particular case, it just makes them white (bolder) which is a minimal change that doesn't serve a greater purpose. But in a lot of cases, including mine, it completely overrides my color coding which throws me off at the muscle memory level.

**Comment by lstein** [comment]
Ok, I'll revert and we'll do some systematic color coding when we implement the correct system of info, warning and error messages.

**Review by lstein — APPROVED** [review]
LGTM (*sniff* *sniff*)

**Comment by lstein** [comment]
By the way, @blessedcoolant, GitHub is asking me to name a successor. I guess the project has gotten too many stars. Would you be willing to be a co-administrator of this repository?

**Comment by blessedcoolant** [comment]
> By the way, @blessedcoolant, GitHub is asking me to name a successor. I guess the project has gotten too many stars. Would you be willing to be a co-administrator of this repository?

Sure. That would be great. Hopefully this is a changeable option incase one of us decides to move on at a later time. But I plan to stick around. Thanks for asking. :)

**Comment by lstein** [comment]
The downside of making a side request in a PR comment is that if you forget which PR it was, it can be hard to find the response! I've been searching on and off for the last few days and finally found it!

I'm so happy you've accepted. I'll update your permissions now. Sorry if it appeared I got cold feet or something.

**Comment by blessedcoolant** [comment]
> I'm so happy you've accepted. I'll update your permissions now. Sorry if it appeared I got cold feet or something.

Haha. No issues.

Maybe we should setup a discord or something for this repo.

**Comment by lstein** [comment]
Actually...there is one as of yesterday! The link is now in README.md (in development).

I checked the permissions page, and it looks like I have to migrate this repository to an organization in order to have more than one maintainer. Is this correct? It's probably time to do that anyway.

**Comment by blessedcoolant** [comment]
> Actually...there is one as of yesterday! The link is now in README.md (in development).
> 
> I checked the permissions page, and it looks like I have to migrate this repository to an organization in order to have more than one maintainer. Is this correct? It's probably time to do that anyway.

Honestly I have no idea how that system works.

**Pull request merged**
