### PR TITLE
Add support of RealESRGAN for Apple M1

### PR DESCRIPTION
**Pull request by glonlas**
This PR:
- [x] Add support of Real ESRGAN for M1 users.
- [x] Update `README-Mac-MPS.md` to add commands to install Real ESRGAN for M1 users.
- [x] Trivial refactoring for the output folder. Using a "constant" instead of repeating the value a two places in the code
- [x] Add `gfpgan/` in `.gitignore` to avoid pushing GFPGAN model weights

**Test**
This PR has been **manually** tested to generate x2 and x4 upscaling via Real ESRGAN, with and without GFPGAN.

### CODE REVIEW

**Comment by Any-Winter-4079** [comment]
`superman dancing with a panda bear -U 2 0.6`  -m ddim works (2x upscale)

**Review by Any-Winter-4079 — CHANGES_REQUESTED** [review]
@glonlas Everything works except for the small fix of >= 4 for 3x upscales. Aside from that, should GFPGAN work on its own too (without upscaling)?. Right now, it only works for me with upscaling (though it's not a big deal because I can always use face restoration if using upscaling).

**Comment by glonlas** [comment]
Thank you for the review. Please DO NOT merge. I will address all comments shortly.

**Comment by lstein** [comment]
The face fixing is supposed to work independently of upscaling. Is this not the case with M1? 

I won't merge until you give the heads up. You might want to convert to a draft to indicate you are still making changes, though!

**Comment by Any-Winter-4079** [comment]
> The face fixing is supposed to work independently of upscaling. Is this not the case with M1?
> 
> I won't merge until you give the thumbs up. You might want to convert to a draft to indicate you are still making changes, though!

@lstein Yes, I agree. Ideally it should be separate, but at least as a last resort we could always use face restoration after upscaling on M1. It's probably a bug somewhere what doesn't let face restoration work on its own, but haven't looked very deeply since @glonlas is on it already. I'm working on doggettx-optimizations in the meantime.

**Comment by glonlas** [comment]
# Update
The last commits fixe:
1. The assumption that we had only x2 and x4. I missed that x3 was possible since the UI proposes only x2 and x4. A future PR will fix the UI options.
2. The bash script was indeed not working. I should have tested it.

# Test:
**Test 1: no face restoration, no upscale** `superman dancing with a panda bear -m ddim -s 8 -S 254908250`
Successful

**Test 3: no face restoration, 2x upscale:** `superman dancing with a panda bear -U 2 0.6 -m ddim -s 8` 
Successful

**Test 3: no face restoration, 3x upscale:** `superman dancing with a panda bear -U 3 0.6 -m ddim -s 8`
Successful

**Test 4: no face restoration, 4x upscale:** `superman dancing with a panda bear -U 4 0.6 -m ddim -s 8`
Successful

**Test 5: face restoration, no upscale:** `superman dancing with a panda bear -G 0.8 -m ddim -s 8 -S 254908250`
Successful

**Test 6: face restoration, 2x upscale:** `superman dancing with a panda bear -U 2 0.6 -G 0.8 -m ddim -s 8 -S 254908250`
Successful

**Test 7: face restoration, 3x upscale:** `superman dancing with a panda bear -U 3 0.6 -G 0.8 -m ddim -s 8 -S 254908250`
Successful

**Test 8: face restoration, 4x upscale** `superman dancing with a panda bear -U 4 0.6 -G 0.8 -m ddim -s 8 -S 254908250`
Successful

**Comment by Any-Winter-4079** [comment]
Okay, finally got it to work.
I will post here my results and comments.

**Comment by Any-Winter-4079** [comment]
`Robert de Niro portrait dressed as Superman -m ddim -s 50 -S 25490825` Left natural, Right -G 0.7 (face restoration)

Screenshot 2022-09-08 at 20 59 23

**Review by Any-Winter-4079 — APPROVED** [review]
As a note on architecture and `GFPGAN`, I seemingly had to switch to `arm64` to run it successfully (while this repo can run with `x86` or `arm64`). 

Maybe it was just that my computer that was messed up, but if more people experience the same (can't run GFPGAN, need to switch to `arm64`), we could potentially update the [instructions](https://github.com/lstein/stable-diffusion/blob/main/README-Mac-MPS.md) in the future.

For now, I've tested it and it works. I think it can be merged, although it would be good if @lstein could run it to make sure it still works on CUDA (it should, no change was made).

Awesome job!

**Comment by Vrk3ds** [comment]
just followed your instructions from above and face resto works!, what doesn't for me is still when trying to upscale the image. I get the following error:

Real-ESRGAN Upscaling seed:25490825 : scale:2x
>> Error running RealESRGAN or GFPGAN. Your image was not upscaled.
'NoneType' object has no attribute 'enhance'

**Comment by Any-Winter-4079** [comment]
@Vrk3ds Do you have a `realesrgan` directory sibling of stable-diffusion? With realesrgan-ncnn-vulkan inside (with executable permissions) and the models folder as well.

**Comment by Vrk3ds** [comment]
> @Vrk3ds Do you have a `realesrgan` directory sibling of `stable-diffusion`? With `realesrgan-ncnn-vulkan` inside (with executable permissions) and the `models` folder as well.
> 
> With that and the 2 files modified in this PR, using the development branch, it should work. Let me know!

I don’t have realesgran in a separate directory just in the stable-diffusion one. I’ll move it and test and let you know

**Comment by Vrk3ds** [comment]
> @Vrk3ds Do you have a `realesrgan` directory sibling of `stable-diffusion`? With `realesrgan-ncnn-vulkan` inside (with executable permissions) and the `models` folder as well.
> 
> With that and the 2 files modified in this PR, using the development branch, it should work. Let me know!

hmmm I am still getting the same error?

image
 this is my folder setup now?

Does that look correct?

**Comment by Any-Winter-4079** [comment]
Try with the name in lowercase, `realesrgan`

**Comment by Vrk3ds** [comment]
> Try with the name in lowercase, `realesrgan`, since the subprocess run searches for lowercase
> Screenshot 2022-09-09 at 01 39 33

still doesn't work?

Do I need to update any other files to make it work?

**Comment by Any-Winter-4079** [comment]
`git checkout development`
`git pull`

Update
Screenshot 2022-09-09 at 12 49 25

`ldm/generate.py` and `ldm/gfpgan/gfpgan_tools.py` with the files from the photo above
With that and the arm64, you should be set there.
You already have these directories

Screenshot 2022-09-09 at 12 48 30

with the model/s inside `realesrgan`

Screenshot 2022-09-09 at 12 51 45
In GFPGAN/experiments/pretrained_models I assume you have the model/s too
Screenshot 2022-09-09 at 12 53 27

and I assume with the arm64 environment activated (e.g. `conda activate do_not_touch-osx-arm64-stable-diffusion`), you  did `cd GFPGAN`,  `pip install -r requirements.txt` and `python setup.py develop`

If you have all of this let me know.

**Comment by Any-Winter-4079** [comment]
Given your error, it looks like it's failing here
Screenshot 2022-09-09 at 13 07 07

**Comment by Any-Winter-4079** [comment]
> not sure what was borked but I manually cut and pasted that code into those two files and now everyone is working!
> 
> Thank You!

Yep, that's what I did. Glad it worked!

**Comment by tilmanginzel** [comment]
Just want to confirm that this pull request works for me on Macbook Air M1. I checked out the branch from `glonlas/stable-diffusion:fix_m1_real_esrgan` and followed the installation instructions. My tests last night (only x2 x3 x4 upscaling, no face restoration) were successful. :)

@Vrk3ds @Any-Winter-4079 Problem might have been that you checked out the `lstein/stable-diffusion:development` branch instead of the branch from this pull request `glonlas/stable-diffusion:fix_m1_real_esrgan`?

**Comment by lstein** [comment]
Will test this later today.

**Comment by glonlas** [comment]
I will also catchup on the thread today.

**Comment by glonlas** [comment]
> > Try with the name in lowercase, `realesrgan`, since the subprocess run searches for lowercase
> > Screenshot 2022-09-09 at 01 39 33
> 
> still doesn't work?
> 
> Do I need to update any other files to make it work?

You might not have all the dependencies installed. Have you followed the instruction in the README to install Real-ESRGAN?
It is the easiest why to install it.

As a reminder:
```bash
# download and install Real-ESRGAN
REALESRGAN_GITHUB_URL="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-macos.zip"
REALESRGAN_ARCHIVE="realesrgan.zip"
REALESRGAN_PATH="realesrgan"
mkdir $REALESRGAN_PATH
cd $REALESRGAN_PATH
curl -L $REALESRGAN_GITHUB_URL -o $REALESRGAN_ARCHIVE
unzip $REALESRGAN_ARCHIVE
rm $REALESRGAN_ARCHIVE
chmod u+x ./realesrgan-ncnn-vulkan
```

**Comment by glonlas** [comment]
If no other concerns, I recommend to +1 and merge so we can move forward and have upscale working on M1 as well :)

**Comment by psychedelicious** [comment]
Confirmed working on M1, thanks!

**Comment by glonlas** [comment]
@lstein @Any-Winter-4079 I am closing this PR as the implementation is too complex while a simpler solution is possible. 
If it does not work on MPS/M1 is because a condition we have in the code. 

This [PR propose a better implementation](https://github.com/lstein/stable-diffusion/pull/474/files), but need a better refactoring.

**Pull request closed without merging**
