### PR TITLE
Add bare bones web UI

### PR DESCRIPTION
**Pull request by TesseractCat**
This PR adds a simple Web UI that allows users to generate images remotely using the simplet2i interface.

TODO:
- If the `txt2img` function gets a progress callback parameter, I could add a progress bar.
- ~~img2img~~
- iterations
- Configurable sampler

### CODE REVIEW

**Comment by lstein** [comment]
Wow. This is fantastic. Thank you. 
I am not going to merge your PR just yet because I am 90% of the way through a code refactoring, and would like to resolve conflicts just once. Will happen Thursday or Friday, depending on how busy I get.

**Comment by SergioDiazF** [comment]
Hi! I'm working on the UI design, so I'd love to include it if you like!

Captura de pantalla 2022-08-25 105115

**Comment by vinyvince** [comment]
Would it not be worth integrating https://github.com/hlky/stable-diffusion-webui with GFPGAN face restoration option ?

**Comment by lstein** [comment]
The web server is very impressive work. Thank you! A couple of changes I made during merging:
1. The "batch" option uses a large amount of memory, scaling linearly with the number of images being produced. "iterations" is a little slower, but only uses the amount of memory that it takes to produce one image. So I changed batch to iterations throughout in order to avoid lots of user complaints on low-memory machines.
2. I moved the static HTML file into a top-level directory named static. I've started using this directory to store other static stuff, such as embedded images in the README. (oops, I just saw that there are .js and .css files that need to move to. fixing...)

Some questions and suggestions:
1. Does the server do garbage collection of the images that it generates and stores locally, or is this something that users should be aware of and clean up periodically?
2. It would be nice to print the seed under each image.
3. On my machine when I resize the web browser to full monitor width, the layout stays fixed. Can the width available for the images be increased?

**Comment by TesseractCat** [comment]
Thanks for merging! To answer your questions:

1. No it keeps the images around for now, I like it this way as I can go back and look through the images I generated, but maybe it could be a command line flag.
2. Right now, the seed and prompt is put in the `title` attribute of each image, so you can hover over each image and see the seed. You can also click on images to restore their generation settings (including seed).
3. Yeah, right now it's fixed at a max-width of 1000px, but this could be changed to be a percentage. I initially had it at 60% but it caused issues on mobile.

Also, maybe it would be possible to have both batches and iterations as settings? I like to set batches as it's only a little slower, but outputs multiple images at once. Maybe 'Iteration Count' and 'Batch Size (Warning high VRAM usage)'.

**Comment by 1blackbar** [comment]
This looks great already, do You plan to include inpainting into the UI ?

**Comment by namion** [comment]
Hi, I'm brand new to github and I don't have any coding experience so I hope it is ok for me to comment (not sure of the etiquette for noobs like myself chiming in). This is my first time installing and using python/anaconda/github, just to give you an idea of how fresh I am. I'm diving in because I'm so impressed with this technology and where it is heading. 

I love the progress on this branch and the new web UI is great but I noticed it is missing a field for the strength parameter for img2img usage. I know how impactful that parameter can be so I was wondering if it would be added in the future? Or am I overlooking something? Thank you all for the amazing work you are doing.

**Pull request merged**
