### PR TITLE
remove support for batch_size from dream.py

### PR DESCRIPTION
**Pull request by bakkot**
Per https://github.com/lstein/stable-diffusion/issues/204, this doesn't seem to be getting much use. It's annoying because the later images do not have a recoverable seed - that's both a bad experience for users and problematic internally because it means you end up with multiple images with the same seed/config.

I haven't changed any of the more "backend" code, like the diffusers; training and everything should work just the same as before. This only effects the `dream.py` and `simplet2i` wrappers.

PngWriter still has some code which refers to batch_size, but that code is in need of further refactoring, which I'll get to after this.

### CODE REVIEW

**Review by lstein — APPROVED** [review]
So nice to see the line count decreasing for a change! Thanks for removing this unmourned feature.

**Comment by BassJMagan** [comment]
sliiightly mourned but only used in cases i was generating a lot of stuff at once. I think it reduced the time to make huge batches of images by about 10-15% give or take

**Comment by noise-puppeteer** [comment]
I've been experimenting with batch sizes in comparison with AUTOMATIC1111's implementation. 

From a few experimentations on a GTX 1080, I've discovered rather replicably that increased batch sizes (for GPUs that support it) can significantly cut down generation times; e.g. a batch size of 4 (compared to 4 iterations of 1) can cut down generation times from 20%-40%. When generating a large number of images, the time reduction is even more prominent. 

Was surprised to discover that this feature has been removed from InvokeAI's implementation. Would have been great if this feature was still around, but I understand the difficulty presented by conflicting/unrecoverable seed values and how this makes SD non-deterministic.

**Comment by BassJMagan** [comment]
yeah, since switching to automatic1111 i only do things in batches of like 6 because of the huge speed increase on an RTX 3090.

**Pull request merged**
