### PR TITLE
fix init_image size to --width --height

### PR DESCRIPTION
**Pull request by nicolai256**

### CODE REVIEW

**Comment by nicolai256** [comment]
seems like there's still an issue, wait with the migration of this request

**Comment by nicolai256** [comment]
okay so it seems like you disabled the image size command in img2img but don't know where/how to disable it.

so that's why it doesn't work, i've written a bit of sample code around line 510 for enable and disable. 
doesn't work yet because i don't know where to enable `init_img -W -H` but could be handy if input image is too big or small and choosing another aspect ratio etc.
will upload the modded code in a minute

**Comment by BlueAmulet** [comment]
You seemed to have changed the line ending of ldm/simplet2i.py from LF (Unix) to CRLF (Windows), causing the entire file to show up as modified, rather than the actual changes.

**Comment by nicolai256** [comment]
> You seemed to have changed the line ending of ldm/simplet2i.py from LF (Unix) to CRLF (Windows), causing the entire file to show up as modified, rather than the actual changes.

oh damn sorry, the actual changes are at line 510 
and 
import PIL

**Comment by BlueAmulet** [comment]
If you have Linux or Git Bash, just run dos2unix on the file and then commit it to fix. Notepad++ also has "Edit -> EOL Conversion -> Unix (LF)" on the menu.

**Comment by nicolai256** [comment]
notepad++ didn't seem to work
and i don't have linux

**Comment by BlueAmulet** [comment]
It has the right line endings now but you put the new simplet2i.py in the wrong folder, now there are two of them.

**Comment by lstein** [comment]
@nicolai256 I'm much obliged to you for this PR!

I had a look at this and I think the logic is not quite right. The init_img is being scaled to the width and height specified in the T2I object. However, these are just defaults that the model falls back on if the width and height are not specified as parameters in the call to img2img, and so if the user asks for something larger or smaller, they will not get it explicitly. I think you need to pass the width and height received in the img2img() method to _load_img() rather than let _load_img() take the default values from self.

Please feel free to correct me if I'm misunderstanding.

Also, be aware that I'm refactoring the simplet2i.py module to make it easier to manage, and should be completed with this by the end of the day today. If you don't mind, please make your pull requests against the branch named "big-refactoring". This will make it easier to merge your fixes.

**Comment by lstein** [comment]
I took this code and modified it so that the init image is embedded inside a black rectangle of the requested width and height. This prevents the init image's aspect ratio from changing when the WxH has a different aspect ratio, and gives you the expected letterbox effect. So though I didn't use this PR explicitly, your code went in via PR #214. Thank you so much for your contribution!

**Pull request closed without merging**
