### PR TITLE
add markdown as a log option, more than just dream_log.txt (and can easily extend to html, csv or other format you like)

### PR DESCRIPTION
**Pull request by mefengl**
## log in the plain text makes it hard for me to check the differences between each prompt, so a simple markdown format may help, which looks like this:

image

## you can config it in `scripts/dream.py`

image

> or in the dream command line, but I didn't implement it in the code.

## and extend more formats also in `scripts/dream.py`:

image

### CODE REVIEW

**Review by lstein — CHANGES_REQUESTED** [review]
This looks very useful and I'd be happy to incorporate it into development. 

I have a small request. I'm trying to reduce the size of dream.py by moving code out of it and into modules. Would you like to start a new module named ldm.dream.log and move the markdown logging code into there? I know this is slightly more than you had in mind, but it will help improve the maintainability of the code base.

**Comment by mefengl** [comment]
moved the entire log to ldm.dream.log, so the global variable `output_cntr` looks a little tricky:

image

works fine, though.

can move the command line log back, what do you think?

**Review by lstein — COMMENTED** [review]
This looks fine. My system is currently in a weekend-long maintenance window so I can't do functional testing until Monday. If someone else can do the testing over the weekend, please approve and I'll make the merge.

**Review by lstein — APPROVED** [review]

**Comment by tildebyte** [comment]
Please flatten your "fix" commits - there's no need to have development process commits in the main commit history (obviously PRs *containing* fixes for main would be different)

**Comment by mefengl** [comment]
@tildebyte 
don't know how to do, so I recreate a pulling with clean commit -- https://github.com/lstein/stable-diffusion/pull/663

**Comment by tildebyte** [comment]
@mefengl; Thank you so much for doing that! If you have any questions about using git in the future, don't hesitate to ask. Also we have a Discord now (https://discord.com/invite/htRgbc7e) - you could also try there to see if someone can help.

**Pull request closed without merging**
