### PR TITLE
Allow configuration of which SD model to use

### LINKED ISSUE #49: Allow loading of different weight files
It would be great if I could specify weight file during script launch, like so:

python scripts/dream.py --model=sd13
python scripts/dream.py --model=sd14
python scripts/dream.py --model=sd12
python scripts/dream.py --model=sd11
python scripts/dream.py --model=sd13_leaked

This command should go to folder \models\ldm\stable-diffusion-v1\ and find a file with exact name passed in argument list + add ".ckpt" extension to it to load a model.

The reason for this request is that all these models produce slightly different images for the same Seed and prompt and the latest version is not the best one for all prompts.

### PR DESCRIPTION
**Pull request by maddavid123**
Closes #49 The syntax isn't quite the same (opting for --weights over --model), rationale being that --weights is more in-line with the existing naming convention.

An outstanding concern is whether the config/v1-inference.yaml will change, although I'm of the opinion that if it does need to change, adding an argument flag is simple, and at this point in time unnecessary.

Both of the below are valid:
--weights SD13 
--weights C:/StableDiffusion/models/ldm/stable-diffusion-v1/SD13.ckpt

### CODE REVIEW

**Comment by lstein** [comment]
@maddavid123 I've reviewed and all looks good, and will merge with main.

I'm thinking that there's probably a more general solution to the issue of new models appearing (I know that 1.5 is imminent). What would you think about having a global JSON or YAML configuration file that attaches a label to the pairing between a weights file and its configuration file? Something along these lines:

~~~~
{
   "laion400m":
           { 
                "config": "configs/latent-diffusion/txt2img-1p4B-eval.yaml",
                "weights": "models/ldm/text2img-large/model.ckpt",
                "width": 256,
                "height": 256
           },
  "stable-diffusion-1.4":
      { 
                "config": "configs/stable-diffusion/v1-inference.yaml",
                "weights": "mmodels/ldm/stable-diffusion-v1.4/model.ckpt",
                "width": 512,
                "height": 512
           },
  "stable-diffusion-1.5":
      { 
                "config": "configs/stable-diffusion/v1-inference.yaml",
                "weights": "mmodels/ldm/stable-diffusion-v1.5/model.ckpt",
                "width": 512,
                "height": 512
           }
}
~~~~

Then we select whichever model we want using --model=stable-diffusion-1.5.

Interested in working on this?

**Review by lstein — APPROVED** [review]
Looks good.

**Comment by maddavid123** [comment]
I do think that utilising yaml or some similar data format would probably be the most scalable approach here. 
Sounds good. Will take a crack at this tonight, should be simple enough considering OmegaConf is already being imported.

**Comment by maddavid123** [comment]
Any preference where in the repo the yaml file lives?
Also, if we are to go with a yaml file approach, do we wish to deprecate --weights & --laion400m? Or do we wish to support these in tandem?

**Pull request merged**
