### PR TITLE
Documentation for negative prompts

### PR DESCRIPTION
**Pull request by BrentOzar**
Documentation for pull lstein#661, and splits prompt docs into a separate file since they're going to get big quickly with these features.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Make a pull request to my PR instead. I can just add it there. Thank you.

**Comment by BrentOzar** [comment]
> Make a pull request to my PR instead. I can just add it there. Thank you.

Thanks, will do in a few hours when I land. (Working on airplane wifi, and I can't figure out how to make a PR to your branch without re-uploading the images, which took forever.)

**Comment by blessedcoolant** [comment]
> > Make a pull request to my PR instead. I can just add it there. Thank you.
> 
> Thanks, will do in a few hours when I land. (Working on airplane wifi, and I can't figure out how to make a PR to your branch without re-uploading the images, which took forever.)

You will probably need to reupload. Pull my PR from here, fork it and make your doc changes and make a PR to me. I'll approve them.

**Comment by blessedcoolant** [comment]
Do not make the other PR. That has already been merged. I'll take a look at these docs and approve.

**Comment by lstein** [comment]
Oh shoot. Sorry. I did not realize this was pending.

**Review by blessedcoolant — APPROVED** [review]

**Comment by blessedcoolant** [comment]
> Oh shoot. Sorry. I did not realize this was pending.

It's all god Lincoln. You can merge this too. It's good to go.

**Review by lstein — APPROVED** [review]
This looks good to me. I"ll wait for @blessedcoolant 's blessing before merging.

**Comment by blessedcoolant** [comment]
@lstein  It's good to go. Merge it up. :)

**Pull request merged**
