### PR TITLE
Switch to regular pytorch channel and restore Python 3.10 for Macs.

### PR DESCRIPTION
**Pull request by corajr**
Although pytorch-nightly should in theory be faster, it is currently
causing increased memory usage and slower iterations:

https://github.com/lstein/stable-diffusion/pull/283#issuecomment-1234784885

This changes the environment-mac.yaml file back to the regular pytorch
channel and moves the `transformers` dep into pip for now (since it
cannot be satisfied until tokenizers>=0.11 is built for Python 3.10).

I tried to update the tokenizers package (https://github.com/conda-forge/tokenizers-feedstock/pull/51)
but ran into some build failures; I'll try to fix those and then move `transformers`
into the conda-forge deps.

### CODE REVIEW

**Comment by jroxendal** [comment]
I can confirm that this PR works really well for me on MBP m1 max (32GB memory) with render times at around 35seconds. Thanks for the hard work.

**Comment by lstein** [comment]
@magnusviri, could you have a look?

**Comment by magnusviri** [comment]
I am really confused. [This comment](https://github.com/CompVis/stable-diffusion/issues/25#issuecomment-1223068308) is why we switched to pytorch nightly. I don't know torch so I don't understand the ramifications of switching. I believe the Denis he is referring to is [DenisVieriu97](https://github.com/DenisVieriu97), who appears to work at Apple on pytorch. I've thought of reaching out to him but I am pretty sure that the pytorch MPS people are aware of us. Didn't this repo make Hacker News? My nephew texted me this morning and said all of his coworkers were running this on their Macs...

**Comment by psychedelicious** [comment]
I've just tested this PR - works fine for me on my 14" M1 Pro. `dream.py` with default settings, prompt "cute dog" runs at 1.05s/it.

**Comment by magnusviri** [comment]
Alright, I've got time. I'll start making tests. I'll first see if this will run in [tart](https://github.com/cirruslabs/tart/). If it will, then this will be really easy to test.

**Comment by corajr** [comment]
Re: the pytorch-nightly thing, I've pasted the output here to show the speed difference in pytorch-1.12.1 vs. nightly -- for me it's quite pronounced (89s vs 122s for one image): https://gist.github.com/corajr/d18c3dfbbf54541fe029784d25a1c465

So the `aten::index.Tensor` op was implemented for MPS here: https://github.com/kulinseth/pytorch/pull/53

However, other operators still require the CPU (such as `aten::nonzero`). I speculate the potential gains from the index op might be destroyed by having to go back to CPU for those other things, or maybe it's just not very optimized yet.

This need for the CPU fallback lead to PYTORCH_ENABLE_MPS_FALLBACK option being added to the env file in https://github.com/lstein/stable-diffusion/commit/2aa83932728242b05248fada8447506e2fbed9f0.

Notably, the environment-mac.yaml file at that commit (including the `pytorch-nightly` channel) actually installs `pytorch-1.12.1` if you try to create it. This puzzled me for a bit, but I realized it's because the order of the channels was prioritizing `conda-forge` over `pytorch-nightly`:

```
channels:
  - apple
  - conda-forge
  - pytorch-nightly
  - defaults
```

The latest https://anaconda.org/conda-forge/pytorch is 1.12.1, hence that's the version it gets.

In any event, the environment-mac.yaml file is now broken because of the 3.10 requirement from Birch-san's repo as I mentioned in https://github.com/lstein/stable-diffusion/commit/91565970c2c12e5609f7f57d8f267fc30532f609#commitcomment-82950840. So hopefully this will unblock folks, and then a subsequent improvement can be made once the tokenizers lib can be compiled for 3.10

**Comment by seewhy163** [comment]
While running this PR, I got the error below.
I tried to fix it and changed the transformers back to `- transformers==4.21.2`, it can work normally

`RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback):
dlopen(/Users/seewhy/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so, 0x0002): tried: '/Users/seewhy/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

**Comment by corajr** [comment]
@seewhy163

> While running this PR, I got the error below. I tried to fix it and changed the transformers back to `- transformers==4.21.2`, it can work normally
> 
> `RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback): dlopen(/Users/seewhy/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so, 0x0002): tried: '/Users/seewhy/opt/anaconda3/envs/ldm/lib/python3.10/site-packages/tokenizers/tokenizers.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

The incompatible architecture issue suggests you have some Intel packages mixed into your environment, which will cause it to break. Try using `CONDA_SUBDIR=osx-arm64` to force the environment to use only arm64 packages, as mentioned in the README: https://github.com/lstein/stable-diffusion/blob/33936430d0e56228c7c6d310fbc4c094cdaeccb4/README-Mac-MPS.md?plain=1#L27

**Comment by seewhy163** [comment]
> 

I just followed the readme and created the environment. I have also executed this command .

**Review by lstein — APPROVED** [review]
Changes look good to me, but I don't have apple hardware to test on. I am bringing into development and if we get further reports like @seewhy163 's, we can back out.

**Pull request merged**
