### PR TITLE
Fixed grid image not saving

### PR DESCRIPTION
**Pull request by blessedcoolant**
@lstein  Grid image not saving after recent changes has been fixed.

### CODE REVIEW

**Review by SMUsamaShah — APPROVED** [review]

**Comment by SMUsamaShah** [comment]
Line 63 https://github.com/lstein/stable-diffusion/blob/ddc0e9b4d87f9a782c8b5e20e381ab1a2b5558c2/ldm/dream/pngwriter.py#L63 will also produce error. I think you should also pass upscale as 2nd param in there.

**Comment by blessedcoolant** [comment]
> Line 63
> 
> https://github.com/lstein/stable-diffusion/blob/ddc0e9b4d87f9a782c8b5e20e381ab1a2b5558c2/ldm/dream/pngwriter.py#L63
> 
> will also produce error. I think you should also pass upscale as 2nd param in there.

Upscaled is defaulted to False. When no argument is supplied, it should take in the value of False. Should be fine I think?

**Comment by SMUsamaShah** [comment]
I think it won't work because previousPath should be the 3rd arg, not the second one. Unless python knows previouspath should be passed into 3rd one it should work. Otherwise it should be `return self.unique_filename(seed, upscaled, previouspath) `

**Comment by blessedcoolant** [comment]
> 

HMm.. Updated it anyway. Just to be sure.

**Comment by tildebyte** [comment]
Yeah, the signature is ` unique_filename(self, seed, upscaled, previouspath=None)`, so those first two are non-optional

**Pull request merged**
