### PR TITLE
Adding support for .bin files from huggingface concepts

### PR DESCRIPTION
**Pull request by chromaticist**
Gets HuggingFace textual inversion .bin files to work in the same way as .pt files by lightly modifying embedding_manager.py. Also prints the new term(s) that were added, because it's not obvious from file names. #427 

Use or generate .bin files from https://huggingface.co/sd-concepts-library

Invoke the same way as .pt files, ie:
`python ./scripts/dream.py --embedding_path "path/to/huggingface_embed.bin"`

Note: I commented out the "more than a single token" assert because it seemed overly prohibitive, but not sure if there's good reasons I'm overlooking to keep that check in there.

### CODE REVIEW

**Review by lstein — CHANGES_REQUESTED** [review]
Nice feature. Could you add a line to the README.md section on textual inversion which points people to the hugging face textual inversion generation capabilities and showing them how to load .bin files? After this, I'm happy to merge.

**Review by lstein — APPROVED** [review]
Thank you! Nice feature.

**Comment by fofr** [comment]
Trying this feature with a `.bin` file from HuggingFace, on an M1 Mac.

When starting `dream.py` I see:
> Added terms: *, <character-pingu>

But when prompting with either:
- a picture of *
- a picture of <character-pingu>

There is no recognition of the trained thing.

Is this an issue with this PR, or are there known issues with textual inversion on a Mac?

**Comment by enjalot** [comment]
thanks for this! for some reason (on my M1 mac) i get a weird error when loading some embeddings but not others. when I load [cat-toy](https://huggingface.co/sd-concepts-library/cat-toy/tree/main)
I get ```RuntimeError: src_total_size >= (src.storage_offset() * src.element_size()) INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1662707511415/work/aten/src/ATen/native/mps/operations/Copy.mm":183, please report a bug to PyTorch.```

but it works fine with [ugly-sonic](https://huggingface.co/sd-concepts-library/ugly-sonic/tree/main)

(just realized that the embedding file for cat-toy is 151mb which doesn't seem right.)

**Comment by chromaticist** [comment]
> thanks for this! for some reason (on my M1 mac) i get a weird error when loading some embeddings but not others. when I load [cat-toy](https://huggingface.co/sd-concepts-library/cat-toy/tree/main) I get `RuntimeError: src_total_size >= (src.storage_offset() * src.element_size()) INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1662707511415/work/aten/src/ATen/native/mps/operations/Copy.mm":183, please report a bug to PyTorch.`
> 
> but it works fine with [ugly-sonic](https://huggingface.co/sd-concepts-library/ugly-sonic/tree/main)
> 
> (just realized that the embedding file for cat-toy is 151mb which doesn't seem right.)

Strange, the embeddings file shouldn’t be 151mb, about 4kb seems average. You’re getting expected results with <ugly-sonic> on your M1?

**Comment by chromaticist** [comment]
> Trying this feature with a `.bin` file from HuggingFace, on an M1 Mac.
> 
> When starting `dream.py` I see:
> 
> > `Added terms: *, <character-pingu>`
> 
> But when prompting with either:
> 
> * `a picture of *`
> * `a picture of <character-pingu>`
> 
> There is no recognition of the trained thing.
> 
> Is this an issue with this PR, or are there known issues with textual inversion on a Mac?

I get expected results on Windows when using `<character-pingu>` from https://huggingface.co/sd-concepts-library/character-pingu/tree/main, but I don't have a Mac to test with :(

For example, initializing:
`python ./scripts/dream.py --embedding_path "path/to/pingu.bin"`

and then running:
`<character-pingu> -s20 -Ak_lms -S2288996774`

gives me:


Does that not reproduce for you? Would need someone familiar with the Mac side of things to debug any differences.

**Comment by fofr** [comment]
@chromaticist Thanks, I've tried again with `ugly-sonic` and it's working. Re-downloaded `pingu.bin` and I also get similar results.

**Comment by lstein** [comment]
Hey @chromaticist, have you tried to generate textual inversion .pt files with this distribution? On my system, I cannot confirm that it works as described in the documentation original authored by @Oceanswave .

**Comment by chromaticist** [comment]
> 

I cannot train .pt on my system either as I get cuda out of memory errors (8gb vram), which was my motivation for adding the .bin support.

**Comment by Oceanswave** [comment]
@lstein https://github.com/AUTOMATIC1111/stable-diffusion-webui-feature-showcase#textual-inversion mentions this repo for training, but things have seem to have broken since then

**Pull request merged**
