### PR TITLE
API server and updated static site

### PR DESCRIPTION
**Pull request by Kyle0654**
Adding Flask + Socket.IO Server with dependency injection, queued job processing, paged history, and metadata storage in files.

### CODE REVIEW

**Comment by Kyle0654** [comment]
@lstein @psychedelicious Would appreciate a review so I can work on any changes =)

**Comment by Kyle0654** [comment]
Alright I've rebased on development (again). Should be ready for review.

**Comment by lstein** [comment]
This is now merged into development.

**Comment by Kyle0654** [comment]
I noticed you restored the static files to the old version. Was the new stuff not working? I'll have no interface without those =(.

**Comment by psychedelicious** [comment]
@Kyle0654 I think the issue was related to my PR which included your old files, I hadn't figured out how to remove them from my PR by the time it was merged. Sorry!

**Comment by Kyle0654** [comment]
I had included new ones in my PR, but they were reverted shortly after =/

**Pull request closed without merging**
