### PR TITLE
Bug Fixes: generate and dream refactor

### PR DESCRIPTION
**Pull request by blessedcoolant**
A bug fix patch for things that broke with the generate and dream refactor. #534 

**Fixes:**

- Fixed `q` not working to exit the dream command line.
- Added `--sampler' to model_group too. This is an important argument that allows scripts to run a default sampler at boot.
- Fixed `generate` ignoring the width and height from the config file.
- Fixed some missing imports
- Fixed some opts not ported over correctly.

**ToDo:**

- **CRITICAL** >>> 2nd Prompt is Broken. The first prompt works. The 2nd prompt crashes. @lstein Please look into this.

---

This bug fix patch can be merged once all the bugs are fixed.

### CODE REVIEW

**Comment by lstein** [comment]
I've got my build environment back (got some time on another university's cluster). I can't reproduce a crash on the second prompt. Do you mean that the first prompt of a session works and the second one fails? Could you paste in a screen grab or transcript?

I am very anxious to get things stable again, so will check back.

**Comment by blessedcoolant** [comment]
> Do you mean that the first prompt of a session works and the second one fails?

Yes.

Here's the trace.

```
Traceback (most recent call last):
  File "scripts\dream.py", line 357, in <module>
    main()
  File "scripts\dream.py", line 95, in main
    main_loop(gen, opt, infile)
  File "scripts\dream.py", line 214, in main_loop
    file_writer = PngWriter(current_outdir)
  File "ldm\dream\pngwriter.py", line 20, in __init__
    os.makedirs(outdir, exist_ok=True)
  File "C:\Anaconda\envs\diffusion\lib\os.py", line 208, in makedirs
    head, tail = path.split(name)
  File "C:\Anaconda\envs\diffusion\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Review by lstein — APPROVED** [review]
Thanks for quickly finding and resolving these bugs. I am testing on my (new!) system now and will try to track down and fix the crashing you observed.

**Comment by lstein** [comment]
> > I can't reproduce a crash on the second prompt. Do you mean that the first prompt of a session works and the second one fails?
> 
> Yes. Crashes for me 100% of the time.
> 
> Steps:
> 
> 1. Enter a prompt. Let it run.
> 2. Press up and run same command again.
> 3. Crash.
> 
> Here's the trace.
> 
> ```
> Traceback (most recent call last):
>   File "scripts\dream.py", line 357, in <module>
>     main()
>   File "scripts\dream.py", line 95, in main
>     main_loop(gen, opt, infile)
>   File "scripts\dream.py", line 214, in main_loop
>     file_writer = PngWriter(current_outdir)
>   File "ldm\dream\pngwriter.py", line 20, in __init__
>     os.makedirs(outdir, exist_ok=True)
>   File "C:\Anaconda\envs\diffusion\lib\os.py", line 208, in makedirs
>     head, tail = path.split(name)
>   File "C:\Anaconda\envs\diffusion\lib\ntpath.py", line 185, in split
>     p = os.fspath(p)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```

Interesting. I'd found and fixed that one earlier today before I committed. I must not have fixed it correctly.

**Comment by blessedcoolant** [comment]
> Thanks for quickly finding and resolving these bugs. I am testing on my (new!) system now and will try to track down and fix the crashing you observed.

Thanks. I'll continue the process of bug checking. If anything pops up, I'll pull up PR's or bring you in.

**Comment by lstein** [comment]
Ok, I got the bug. Will fix one other minor thing I noticed and then commit.

**Pull request merged**
