### PR TITLE
TOIL(requirements): Split requirements to per-platform

### PR DESCRIPTION
**Pull request by tildebyte**
I had been thinking about doing this anyway, and then I saw 18cdb55, which will probably break pip installs on Windows and Linux - at the very least, I don't think you'd end up with CUDA-enabled torch.

There are comments in the updated requirements files for Win and Lin (at this point they're identical, but this way they can easily diverge if necessary), but TL;DR I've

- Unpinned torch/torchvision and directed pip to resolve the latest CUDA-enabled version for *this* Python on *this* platform (where "*this*" is "the Python in our virtual environment for the OS and processor we're on) - it should work as-is on both Win and Lin - directly from the torch project's wheel repo
- Unpinned numpy - it **must** track the torch version
- Pinned pip itself, as outdated pip can cause no end of problems

### CODE REVIEW

**Comment by lstein** [comment]
This seems very sensible, and I particularly like the comments about one package or another not working so that nobody goes down the same rabbit hole. I'll need a review from at least one other developer, since I am very new to the python requirements game.

**Review by lstein — APPROVED** [review]
Will need another review as well.

**Comment by tildebyte** [comment]
@lstein; Please don't do HEAD merges in PRs. It adds unnecessary commits and confuses the author (well, *me*, at least 😁).

If it's been a while, and there's a drastic divergence, a reminder is probably a good idea, but I try to make sure to check my PRs at least once a day to rebase against whatever the target HEAD is (and that's if there **haven't** been any comments or reviews).

**Comment by lstein** [comment]
> @lstein; Please don't do HEAD merges in PRs. It adds unnecessary commits and confuses the author (well, _me_, at least grin).
> 
> If it's been a while, and there's a drastic divergence, a reminder is probably a good idea, but I try to make sure to check my PRs at least once a day to rebase against whatever the target HEAD is (and that's if there **haven't** been any comments or reviews).

Ok, so you mean "Squash and merge" or "Rebase and merge" and not "Create a merge commit?" My usual workflow is to follow the command line instructions, test that major features are still working, and then do a git merge --no-ff. I guess this is **not** what you want to see?

**Comment by tildebyte** [comment]
"Please don't do HEAD merges in {still open and being worked on} PRs": It's partly my fault; I discovered a couple of issues and should have marked it as "draft" until I was sure it was done.

Once they're approved and ready to merge, then yes squash and merge, unless it looks like it's better to keep the separate commits - then rebase and merge.

**Pull request merged**
