### PR TITLE
Feature: Add Colab Notebook

### PR DESCRIPTION
**Pull request by artmen1516**
Hello, I created this colab notebook to run Dream script in an isolated environment, 
The main reason for this is that I tried to run dream.py locally using cpu (in a Macbook pro) but at the end I couldn't set it up.
So this is an alternative for people who wants to try the Dream script and doesn't have a GPU (like me). 

Changes I made to Repo:
- Add the .ipynb file to root .
- Add a small README section with a shortcut to the notebook. (Feel free to move it to other section)
- Add an image to `/static/` path.

In the notebook I added the steps needed to set up the environment.

This is where the README colab shortcut is going to take you:
https://colab.research.google.com/github/lstein/stable-diffusion/blob/main/Stable_Diffusion_AI_Notebook.ipynb

Obviously, that link won't work until being merged, so to test the notebook you can use this link to the fork I made:
https://colab.research.google.com/github/artmen1516/stable-diffusion/blob/feature/colab-notebook/Stable_Diffusion_AI_Notebook.ipynb

Note: 
Currently in the notebook i'm cloning the repo and checking out to tag [release-1.09](https://github.com/lstein/stable-diffusion/releases/tag/release-1.09) since there are a lot of changes being made, and lastest repo merges were causing the notebook to fail (dream was closing unexpectedly, it was being used a lot more ram memory causing notebook to kill the process, etc.). I don't know if this issues are already resolved, but to not get any unexpected behavior, that approach is being used.

Let me know if this is useful, and if there are changes needed before merging.

Some Notebook screenshots:
colab_notebook

Screen Shot 2022-08-26 at 5 36 24 PM

### CODE REVIEW

**Comment by tildebyte** [comment]
This is a great idea; I'll take a closer look some time this weekend.

@artmen1516; Will you please squash your 6 commits into one?

**Comment by artmen1516** [comment]
Sure!, thanks.

**Comment by tildebyte** [comment]
LGTM, but I can't actually generate anything with it; the dream script gets OOM-killed (because of main RAM usage on a T4 🤨).

I don't have Pro right now, so I can't request a "large memory" instance to fully test it.

**Comment by artmen1516** [comment]
Hello @tildebyte,
hmm that's weird...
i'm not using Colab Pro, I get 12Gb RAM by default, and I also get a T4.

I made some debugging, when the dream script is initializing memory rises to 10.7gb of usage, but once it launches it drops to around 1.7Gb, it only rises at startup.
I attach some images about this.
Let me know if you have different settings, or if you could check again, I'm thinking in a different approach...

Memory rise:
Memory rise
Memory drop:
Memory drop
Results:
Results
Notebook settings:
Notebook settings
GPU Assigned:
GPU Assigned

**Comment by tildebyte** [comment]
@artmen1516; Just retried. OF COURSE it works now 🙄 😁

**Review by tildebyte — APPROVED** [review]

**Comment by artmen1516** [comment]
Well, we wouldn't be good IT guys without the famous restart 😆.
IT meme

**Review by lstein — APPROVED** [review]
This looks good to go! Thanks for a nice feature addition.

**Comment by cosalexelle** [comment]
Issues with the Colab notebook: scripts/dream.py seems to be failing to download a file, maybe a model with error 404. 
Screenshot 2022-08-29 at 19 21 10 (2)

**Comment by cosalexelle** [comment]
Update: re-ran the notebook and there is no error!

**Pull request merged**
