### PR TITLE
Create scalable solution for adding new models

### PR DESCRIPTION
**Pull request by maddavid123**
(Submitting as draft as to get some answers to open questions)

models.yaml can serve as a base for expanding our support for other versions of Latent/Stable Diffusion.
Contained are parameters for default width/height, as well as where to find the config and weights for this model.
Adding a new model is as simple as adding to this file.

This is loaded from dream.py with the model name supplied with --model (default being stable-diffusion-1.4)

Breaking changes:
--laion400m probably should be deprecated (or outright removed) off of the back of this pull. (Admittedly, we could retain the --laion400m flag, and simply force it to execute the laion400m model, which wouldn't be a breaking change.)
--weights is more or less useless with this pull, am I good to deprecate it? It was a short lived change, and switching users over should be painless enough.

Finally, defaults:
Given that the weights that everyone (afaik) is reading from is models\ldm\stable-diffusion-v1\model.ckpt, switching it over to reference the weights in a directory specifically for stable-diffusion-1.4 is a massive breaking change.
Should we accept that the de facto location of stable-diffusion-1.4 is in the stable-diffusion-v1 directory?

### CODE REVIEW

**Comment by lstein** [comment]
I think this is the right way to do it. I'll play with your solution a bit and let you know if I see any potential improvements. As for issues of defaults and deprecated switches, we can't change the default location of SD v1.4 weights or there will be massive confusion. --weights and --liaon400m should be deprecated with an error message to use the new --model argument, and both eventually removed.

**Comment by tildebyte** [comment]
Agree with @lstein a.f.a. 'models\ldm\stable-diffusion-v1';  there's an incoming 'stable-diffusion-1.5' (E.T.A. unknown), so clearly the "v1" series is far from played out.

**Comment by lstein** [comment]
This looks good. The only thing I'd do differently is to provide a command-line switch that allows you to select a different location for the master config file. I'll take a crack at that.

**Review by lstein — APPROVED** [review]
Tested and works well.

For a future iterations, I'd suggest adding a "default" option to models.yaml, and adding extra messaging to tell user what options are available. Maybe if they pass --model with an invalid model name (or "help") the code can parse the models.yaml file and print out list of keys.

**Comment by lstein** [comment]
Was merged into development.

**Pull request closed without merging**
