### PR TITLE
GFPGAN and Real ESRGAN Implementation Refactor

### PR DESCRIPTION
**Pull request by blessedcoolant**
Refactored the implementation of GFPGAN and Real ESRGAN. Here's a quick rundown of the changes.

## Structure Changes

- `ldm.gfpgan` folder renamed to `ldm.restoration`
- `ldm/gfpgan/gfpgan_tools.py` fully removed. GFPGAN now runs through `ldm/restoration/gfpgan.py` and ESRGAN runs through `ldm/restoration/realesrgan.py`

---

## Implementation

GFPGAN and ESRGAN are two new classes that control the functionality of the two processes respectively. They are completely independent of `generate`.

You can now call GFPGAN and ESRGAN classes with their respective arguments to initialize them. Then you can run either by performing the `process` method that takes the `image`, `strength` and `seed` (optional) as inputs.

---

## Dream Script Changes

- Two new switches added: `--gfpgan` and `--esrgan` .. They will individually tell the user to enable GFPGAN and ESRGAN respectively.
- If enabled, the dream script will check for the models and files. If there's an error, the app will exit outputting the errors.
- `--gfpgan_bg_upsampler` argument removed. It is obsolete.
- `--gfpgan_bg_tile` renamed to `--esrgan_bg_tile` because that is what it is used for.

To enable GFPGAN users need to pass `--gfpgan` and `--gfpgan_dir` at least.
To enable ESRGAN users need to pass `--esrgan` only.

---

## Generate Changes

- `generate` now takes two new arguments - `gfpgan` and `esrgan` - set to `None` by default.
- If they are not provided, GFPGAN and ESRGAN will be disabled.
- They can be provided by initializing GFPGAN and ESRGAN using the new classes mentioned above. The initialization is done PRIOR to calling `generate`.

---

## Side Effect Fixes

- Fixed the Embiggen Script to work with the new changes.
- Fixed the web server.py to work with the new changes.

---

## Note

- Added placeholders for embiggen in the `server.py`  as they're not officially supported yet and the generation was broken without them. Found this while making the changes I needed to do for this PR.

---

## NOTE

~~**This is only an initial draft. I will tweak and refine it over the next couple of days. Please feel free to test it out and let me know if you spot any bugs.**~~

Think it's good to go now.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
@lstein Got started on it. Will tweak and refine it over the next few days based on feedback. How do you want to implement the post process? I've add a consistent `process` method to both GFPGAN and ESRGAN now as we discussed in the other thread.

**Comment by psychedelicious** [comment]
`seed` is required by both the current and the new ESRGAN and GFPGAN modules. Unless I am missing something, it seems this is used only for logging. 

However, one of the use-cases is to run these processing types independently, in which case, from where do we get the seed? In the new web UI, I have implemented running ESRGAN and GFPGAN independently already, and have to work around this for images without known seeds.

Suggest that the `seed` argument is dropped and instead, logging uses the filename of the image to upload. This is both a more explicit identification of the image being processed anyways.

**Comment by psychedelicious** [comment]
In the web UI, I do not ask `prompt2image` to run ESRGAN/GFPGAN as it feels like lumping in generation with postprocessing. I have my backend script interface with each of ['generate', 'esrgan', 'gfpgan'] independently when needed. If this is not already part of this change (seems like this is in the spirit of this change), I suggest we consider this for future development.

**Comment by blessedcoolant** [comment]
@psychedelicious 

So basically at the moment, I replicated the functionality of the CLI exactly as it is.

> seed is required by both the current and the new ESRGAN and GFPGAN modules. Unless I am missing something, it seems this is used only for logging.

That is correct. It is only used for logging. What I can do is make the seed optional. So that way, you can call GFPGAN and ESRGAN even when there is no seed available -- which is rarely the case when using the CLI because there's no independent scaling and restoration feature.

> In the web UI, I do not ask prompt2image to run ESRGAN/GFPGAN as it feels like lumping in generation with postprocessing. I have my backend script interface with each of ['generate', 'esrgan', 'gfpgan'] independently when needed. If this is not already part of this change (seems like this is in the spirit of this change), I suggest we consider this for future development.

With this change, you can just initiate either GFGPAN or ESRGAN at will without the need for anything else. As long as you have the image in the same format as the `generate` module and a strength specified.

**Comment by blessedcoolant** [comment]
Made an update patch.

- `seed` is no longer required to process. It's optional. `generate` still uses in the CLI but you can call process without any seed now. Just the image and the strength.
- Improved UX logging. The user is clearly told when GFPGAN and ESRGAN are disabled.

**Comment by cmsj** [comment]
@blessedcoolant I grabbed your branch and [updated my dreambot](https://github.com/cmsj/dreambot/commit/d7bb41cea2cbc7d4df87e7153ae1631062cf03a0) to use it. A few tests in and it seems to be working fine. Thanks very much! Looking forward to this merging 😁

**Comment by cmsj** [comment]
This looks to be replaced by #690 right?

**Pull request closed without merging**
