### PR TITLE
FEAT: add notebook for Windows for from-zero install and run

### PR DESCRIPTION
**Pull request by tildebyte**
Tested with JupyterLab and VSCode

This is a little tricky, as the best way to use it it to download and run it **without** first cloning this repo (notebook actually handles that).

I reckon anything involving installing/setting up/using Jupyter/JupyterLab/VSCode (which needs to have notebook support Extensions installed) is out of scope for this repo.

IMHO this is actually superior to a scripted (Powershell/batch ew) install of some kind as

1. It's easier for them (and us) to see *exactly* what went wrong, and exactly *where* it went wrong
2. It gets users used to using notebooks and looking at code

Prerequisites are

- At least one of Jupyter/JupyterLab or VSCode
- Python 3.10
- Git for Windows

Signed-off-by: Ben Alkov <ben.alkov@gmail.com>

### CODE REVIEW

**Review by lstein — CHANGES_REQUESTED** [review]
Could instructions for using this be added to the README.md installation section?

**Comment by tildebyte** [comment]
Absolutely, I wanted to see what you thought about it before taking it any further :)

**Comment by tildebyte** [comment]
@lstein, @blessedcoolant; Synced the README, notebook, and wiki in terms of Windows prerequisites, etc. I decided to leave the existing conda install in the README, as I figure if I remove it, someone will surely come along and ask how to do it 😆

With this, we'll have three options for Windows install.

**Review by lstein — APPROVED** [review]
Thank you!

**Pull request merged**
