### PR TITLE
Add Temp Logo To Repo

### PR DESCRIPTION
**Pull request by blessedcoolant**
Made a temporary logo to the repo header. I'll make a proper one at a later time. But this'll be an identifier for this repo in the meanwhile.

Just a simple idea for now .. literally dreaming prompt to image.

### CODE REVIEW

**Review by tildebyte — APPROVED** [review]
Nice 🎉

**Comment by blessedcoolant** [comment]
There's also a color variant but I'm not too happy with it at the moment. Because this repo is still in development, I felt the black and white logo will indicate that too. Once we're in full flow, I'll make a new one with more thought and time put into it.

icon

**Review by lstein — APPROVED** [review]
Thanks!

**Comment by lstein** [comment]
@blessedcoolant , I was thinking that we're reaching a point where we could have the "proper" logo  you talked about in the original PR. Are you still up for working on it? I'd also like to see a favicon for the web interface.

**Comment by blessedcoolant** [comment]
> @blessedcoolant , I was thinking that we're reaching a point where we could have the "proper" logo you talked about in the original PR. Are you still up for working on it? I'd also like to see a favicon for the web interface.

I'm a little swamped with work for a week or so but I'll try to see if I can work something out.

**Pull request merged**
