### PR TITLE
Add simple variant mechanism

### PR DESCRIPTION
**Pull request by Oceanswave**
This pr adds the following:

 - Introduces a new flag, [-v, --variants] that accepts an int and pipes generated images back through the img2img pipeline in order to have a simple 'variants' method. This obvi has some limitations: works solely on strength, and uses the original prompt, but provides some interesting results
 - Fixes the warning that LANCZOS is deprecated introduced by a different PR
 - Hopefully better resolves the device issue for folks running on different device types in the ddim and plms samplers

### CODE REVIEW

**Comment by morganavr** [comment]
This is a prompt I provided:

> dream> "photo dog labrador park" --init_img=./init-images/dog.png --strength=0.75 -s50 -n1 -v 5

Created variants images are very _different_ from each other. If I remove "-v 5" parameter, script creates images of the same quality. Is it an expected behavior of this PR?

**Comment by lstein** [comment]
Thanks for this. Is there a reason that you created an unused variants argument in the calls to img2img() and text2img()? Is this just to avoid python complaining about an unexpected argument?

**Comment by Oceanswave** [comment]
@morganavr the strength of how closely img2img follows the image is controlled by the -f or --strength flag

@lstein sheepishly yes - open to a better way, delete the property prior to pass?

**Comment by lstein** [comment]
@Oceanswave I'm inclined to leave it be. I just got a little confused because I was looking for the variation-generating code in the simplet2i (which ain't simple any longer) and thought you'd forgotten something. The code is seriously in need of refactoring anyway, and I'm likely going to be changing how arguments are passed to the two routines.

**Comment by morganavr** [comment]
@Oceanswave
my concern with that PR is that even without --variants argument script produces the images of the same variation similarity.
I thought that --variants will produce almost identical images that differ only slightly from each other.

Can you provide a usage example with correct parameters? Also I think that README should be updated because how users are supposed to know about this new feature? :)

**Comment by Oceanswave** [comment]
@morganavr  Sure - 
```
Snap a dog wearing swim goggles and a funny hat at the park -n1 -f0.4 -v5
```

**Comment by Oceanswave** [comment]
@morganavr since this is pretty fun.. here's another
```
Snap a rocket ship made of cheese -n1 -f0.6 -v5
```

**Comment by Oceanswave** [comment]
@morganavr 
```
Snap pancakes that have the outline of a gorilla -n1 -f0.6 -v5
```

burning the pancake to get the effect is... pretty clever..








I like the smiling one with the hand

**Comment by Oceanswave** [comment]
@morganavr 
```
Snap a butterfly with stained glass wings -n1 -f0.6 -v5
```

**Comment by Oceanswave** [comment]
okok, one more.
```
A painting of a beach at night, stars flicker and reflect in the waves, in the style of Thomas Kinkade, ultra realistic -n1 -f0.6 -C 13 -v5
```

**Comment by Oceanswave** [comment]
Reducing the -f or --strength reduces the variation

```
Snap a man wearing a pineapple hat. -n1 -f0.2 -C 13 -v5
```
ezgif-5-917734c1cf

**Comment by Oceanswave** [comment]
And it's possible to supply your own initial image as well -- just using one that is in the repo
```
a photo of a dog sitting on a bench -Idata/inpainting_examples/overture-creations-5sI6fQgYIuo.png -f0.2 -C17.0 -v 5
```
ezgif-2-f3e96ab25d

**Comment by vekst** [comment]
This'll be fun to use, nice one. Somewhat related, but this gives me an idea for something similar but for normal, non img2img generations. A variant command that changes the CFG Scale of a generation which is using a seed. Would be kinda fun.

**Comment by morganavr** [comment]
Thanks for all these examples @Oceanswave
It seems that I used wrong parameters and your feature works as intended!

**Pull request merged**
