### PR TITLE
Add --progress-images to CLI

### LINKED ISSUE #99: Feature request: prompt2image option to output intermediate images
It would be cool if there was a way to see the intermediate results as the sampler creates the image. This could be useful for samplers such as `k_euler_a` which varies quite a bit between steps, as a way to generate variations.

Perhaps the `prompt2image` function could have an `intermediates` parameter, which would be an array of steps to save images at.

So for example, one could call `prompt2image("astronaut riding a horse", steps = 50, intermediates = [10, 20, 30, 40])`.

Here is an example of an intermediate images using the `k_euler_a` sampler at steps 30, 25, 20, and 15:

image

### LINKED ISSUE #154: FEAT: Saving intermediate images
When I generate image with 512x768px size it generates nice image but it takes long time and I was wondering if it's possible to get more images by saving intermediate images as well to a separate folder named exactly as the image generated just without .png

**Why it's useful:**
1) It allows to optimize `steps` parameter with different samplers and different resolutions
2) It allows to see how the image evolves over time

I have created the same Issue in @basujindal fork at https://github.com/basujindal/stable-diffusion/issues/75
I believe this feature could be useful in both forks. I use @basujindal fork to generate max size images on 8GB VRAM GPU and @lstein for anything else.

### LINKED ISSUE #224: Request: Option to show intermediate images in CLI, not just web
Today code to show the generation progress for the web ui was added.

Is it possible to also add this as a CLI switch? Would be very helpful for my use case.

### PR DESCRIPTION
**Pull request by kevinschaul**
Uses similar code to the web GUI for saving intermediate images.

Fixes #75
Fixes #99
Fixes #154
Fixes #224

### CODE REVIEW

**Comment by tildebyte** [comment]
Are you sure this fixes #75?

**Comment by blessedcoolant** [comment]
I did some testing on this. Here are my notes.

1. You need to rebase this on top of the development changes. A lot of refactoring was done. So you'll need to update your code.
2. I did step 1 and realized that the Seed value for saving the images being returned is None. You need to fix that.
3. Even saving an image per step, I did not see any drastic performance loss. It's pretty fast.

But I did notice something.

I know for a fact that `k_euler_a` at 20 steps gives a totally different image when compared to `k_euler_a` at 50 steps for the same seed. I presumed when I save the intermediate images, I will see the transitioning through all these images. But that is not what I see. I see a noisy version of the final output right until the final step when it is a pretty clean version. Irrespective of what step count I use or what sampler I use.

Any reason why that is the case? Why isn't `k_euler_a` generating the different output as it should at different steps?

**Comment by lstein** [comment]
@kevinschaul, thank you so much for contributing this nice feature. As my collaborators have mentioned, it would be best if you could rebase this PR against the development branch. The code is evolving quickly, and over time it becomes increasingly difficult to merge in contributions. I hope you understand.

**Comment by blessedcoolant** [comment]
@kevinschaul @lstein I have a very nice implementation of this feature locally using `-save_progress`. I think I will make a new PR with that feature added to this and add kevin as the co-author.

**Comment by kevinschaul** [comment]
Hi all, apologies I was away from keyboard this weekend. Thanks for all the tips. I'm happy to close this and help get #694 merged instead.

**Pull request closed without merging**
