### PR TITLE
Unconditional/Negative Prompt 

### PR DESCRIPTION
**Pull request by rabidcopy**
In regards to a feature request I made earlier #621. Implements use of unconditional_conditioning through ```-u``` in the dream.py command line interface. Does not add anything to the web interface. (Though I think that's a side effect of using significantly short prompts in this example, so the negative prompt ends up having a lot of influence proportionally.) However I was able to reproduce a proper pika with the use of -```u pikachu```.
```dream> a photo of a pika -Addim -s16 -S100``` (not using the SD 1.4 model but one trained on further)

```dream> a photo of a pika -Addim -s16 -S100 -u pikachu```

Can confirm it works with img2img and gives matching results when compared with https://github.com/AUTOMATIC1111/stable-diffusion-webui using the same parameters, init_img, prompt, negative prompt, and DDIM sampler.
init_img

```a picture of a pet -Addim -s16 -S1 -u dog --strength 0.75 --init_img /notebooks/stable-diffusion/outputs/img-samples/000030.1.png```

### CODE REVIEW

**Comment by blessedcoolant** [comment]
Very nice. I haven't tested it yet. Will do in a bit.

However, would it be possible to implement this in the prompt line itself in some way? That way we can avoid using another argument.

If that would not be possible or out of the scope of this PR, then I'd recommend changing the argument to something that is easier to remember. For example: `-forget` -- In a way implying that you are asking the conditioning to forget the given words.

**Comment by blessedcoolant** [comment]
Seems to be working as intended.

`a photo of a pet`



`a photo of a pet  -forget "dog"`

**Comment by blessedcoolant** [comment]
This is actually working a lot better than I expected.

`first prompt`


`-forget spectacles`



`-forget spectacles guns`



`-forget spectacles guns mustache`


`-forget spectacles guns mustache greg rutkowski`



`-forget spectacles guns mustache greg rutkowski legs`

**Comment by rabidcopy** [comment]
> Very nice. I haven't tested it yet. Will do in a bit.
> 
> However, would it be possible to implement this in the prompt line itself in some way? That way we can avoid using another argument.
> 
> If that would not be possible or out of the scope of this PR, then I'd recommend changing the argument to something that is easier to remember. For example: `-forget` -- In a way implying that you are asking the conditioning to forget the given words.

I'd like it to be passed like prompt weights, but I don't have the know how to go about that code wise, which is why this is a draft because it needs to be implemented more intuitively and less of a hack job.

**Comment by blessedcoolant** [comment]
> I'd like it to be passed like prompt weights, but I don't have the know how to go about that code wise, which is why this is a draft because it needs to be implemented more intuitively and less of a hack job.

Once I started using it, I didn't really mind using `-forget` as a prompt. It felt quite natural. Almost like I had a prompt and I was telling SD to forget some stuff and it was doing just that. The results kind of validated that too.

I think that would be a far more intuitive implementation than trying to get the user to type weight values and stuff like that.

**Comment by SMUsamaShah** [comment]
What will it do if we exlcude/forget the whole prompt?

**Comment by blessedcoolant** [comment]
> What will it do if we exlcude/forget the whole prompt?

Try it and let us know.

**Comment by tildebyte** [comment]
@rabidcopy;

You're trying to merge to 'main'. Please rebase and point at 'development'

**Comment by tildebyte** [comment]
This was just too hilarious to not share (and I might be a little punchy): "cat banana -forget tail green"

**Comment by lstein** [comment]
> > Very nice. I haven't tested it yet. Will do in a bit.
> > However, would it be possible to implement this in the prompt line itself in some way? That way we can avoid using another argument.
> > If that would not be possible or out of the scope of this PR, then I'd recommend changing the argument to something that is easier to remember. For example: `-forget` -- In a way implying that you are asking the conditioning to forget the given words.
> 
> I'd like it to be passed like prompt weights, but I don't have the know how to go about that code wise, which is why this is a draft because it needs to be implemented more intuitively and less of a hack job.

I haven't played with this yet, but it looks terrific. With respect to incorporating this functionality directly into the prompt I take it that you can only forget *one* word or phrase at a time? In that case we definitely wouldn't want it to be part of the prompt, because people will be tempted to do something like:

~~~~
picture of a pet [cat] [dog]
~~~~

(This is making up a syntax in which square brackets are used to indicate the tokens to forget)

I'd just like to get confirmation on this assumption, because if in fact you can downweight multiple tokens at once, it would be worth going the extra mile to incorporate the functionality into the prompt weighting syntax.

**Comment by lstein** [comment]
I just noticed that the PR was made against "main". It needs to be based against development. I have changed the base, but because the argument parsing moved around recently, there are some conflicts. If you have time, could you please modify the PR to go in cleanly against development? If not, I will do it, but it might take a bit longer. :-)

**Comment by rabidcopy** [comment]
> I just noticed that the PR was made against "main". It needs to be based against development. I have changed the base, but because the argument parsing moved around recently, there are some conflicts. If you have time, could you please modify the PR to go in cleanly against development? If not, I will do it, but it might take a bit longer. :-)

Ah, I knew I was probably doing something wrong, I'm not terribly familiar with GitHub and didn't even realize there was a development branch pull requests were going into before being merged into main. I really don't have the qualifications to be putting my code next to this. I see that stuff has been moved around a bit and while I'd like to re-do the PR to for it, I'm currently facing some health issues that have cropped up so I cannot honestly say I can do it.

**Comment by tildebyte** [comment]
@blessedcoolant; Would you be willing to pick this up and PR against dev? I **think** I have it working correctly locally, but I'm not convinced 😂 ...

**Comment by blessedcoolant** [comment]
> I'd just like to get confirmation on this assumption, because if in fact you can downweight multiple tokens at once, it would be worth going the extra mile to incorporate the functionality into the prompt weighting syntax.

It seems like multiple words in `-forget` work. Or at least the above results indicate for me. And I've done the same thing on a few other examples too.

**Comment by blessedcoolant** [comment]
> @blessedcoolant; Would you be willing to pick this up and PR against dev? I **think** I have it working correctly locally, but I'm not convinced 😂 ...

Yep. I'll make a PR in a few mins. Just doing some testing to make sure it works right.

**Comment by tildebyte** [comment]
@rabidcopy;

>  I'm currently facing some health issues that have cropped up

Take care of yourself! We'll still be here when you're feeling better 😃

**Comment by blessedcoolant** [comment]
@rabidcopy It's okay mate. Take care of your health. More important than anything else. Get well soon. And thanks for the PR.

#661 I've implemented it directly into prompts now. Have a look.

@tildebyte #661 -- Here you go.

**Comment by lstein** [comment]
Thanks so much for your contribution @rabidcopy, and take it easy. I see that your code has been incorporated into @blessedcoolant 's new PR, and I will make sure you're included in the contributors list.

**Comment by blessedcoolant** [comment]
> @blessedcoolant 's new PR, and I will make sure you're included in the contributors list.

I took care of that in the PR. Added his name to the Contributors list. :)

**Pull request closed without merging**
