### PR TITLE
optionally scale initial image to fit box defined by width x height

### PR DESCRIPTION
**Pull request by lstein**
In img2img, user has the option of either letting the initial image determine the size of the generated images, or of constraining the image to fit within the box defined by Width and Height.

* This functionality is triggered by the --fit option in the CLI (default
false), and by the "fit" checkbox in the WebGUI (default True)

* In addition, this commit contains a number of whitespace changes to
make the code more readable, as well as an attempt to unify the visual
appearance of info and warning messages.

### CODE REVIEW

**Comment by blessedcoolant** [comment]
I did a quick testing of this last night. I recall the images being the same size no matter what the inputs were. But I was half dazed when I was testing it. I'll test it again after work today. Maybe someone else can double check in the meanwhile.

**Review by tildebyte — APPROVED** [review]
*I have not tested this myself*, but the work LGTM. @lstein, I leave it up to you whether you want to wait for @blessedcoolant before merging.

**Comment by lstein** [comment]
> _I have not tested this myself_, but the work LGTM. @lstein, I leave it up to you whether you want to wait for @blessedcoolant before merging.

Bless you! Thanks.

**Comment by blessedcoolant** [comment]
Been busy yesterday but back now. I tested this PR out. It's a really good solution. Initially I was a bit baffled that `-W` and -`H` weren't working with img2img anymore but then I realized that even if you submit a large res file, it automatically scales it down to a more manageable size.

Great PR @lstein 

One further upgrade to this PR would be to provide the user with an option to specify which attribute should the resizer take when considering resizing.

My default height is set to 768 but the max resolution my comp can handle is 512x768. When I supplied a large image to the resizer, it used my height as the reference and rescaled the image to 640x768. This is larger than my comp can support. In cases like this I'd like to specify a switch to tell the resizer to scale by my default width as reference and not the height.

**Pull request merged**
