### PR TITLE
work around unexplained crash when timesteps=1000

### PR DESCRIPTION
**Pull request by lstein**
For some reason when ddim timesteps hits 1000, we get a crash (Issue #415). This doesn't fix the underlying problem, but it prevents it from happening.

### CODE REVIEW

**Comment by lstein** [comment]
Actually, this doesn't work.

**Comment by lstein** [comment]
This fix seems to work, but needs testing. Please try txt2img functionality using the DDIM sampler with a variety of step lengths. Previously it would crash predictably on steps sizes 27, 101, 108, and 110.

**Comment by Any-Winter-4079** [comment]
Yeah, this solution works. See https://github.com/lstein/stable-diffusion/issues/415#issuecomment-1240492947 for explanation of what happens inside the function.

The question would be: is there any difference in the output images (e.g. quality degradation) removing the +1?
Personally, I didn't find any difference with this solution
`steps_out = ddim_timesteps`
 vs. my solution
`steps_out = np.where(ddim_timesteps != 999, ddim_timesteps+1, ddim_timesteps)`
which if it doesn't work you can reimplement in a way that works in your machine/s (basically, given an array ddim_timesteps, add 1 to all values except when value is 999).

If both are equally good, I think @lstein solution is better simply because it requires less computation.

**Comment by lstein** [comment]
> Yeah, this solution works. See [#415 (comment)](https://github.com/lstein/stable-diffusion/issues/415#issuecomment-1240492947) for explanation of what happens inside the function.
> 
> It's not going to fail at any step because it never reaches 1000 (at least with 'uniform'). The question would be: is there any difference in the output images (e.g. quality degradation) removing the +1? Personally, I didn't find any difference with this solution `steps_out = ddim_timesteps` vs. my solution `steps_out = np.where(ddim_timesteps != 999, ddim_timesteps+1, ddim_timesteps)` which if it doesn't work you can reimplement in a way that works in your machine/s (basically, given an array ddim_timesteps, add 1 to all values except when value is 999).
> 
> If both are equally good, I think @lstein solution is better simply because it requires less computation.

For whatever reason, your original proposed solution wasn't working for me. I can't see any difference in the images so I'm not going to sweat it.

**Comment by Any-Winter-4079** [comment]
No problem :) When it gets merged, we could close this https://github.com/lstein/stable-diffusion/issues/415, to keep things a bit clean.

**Comment by rickyars** [comment]
> 

why doesn't this work for me? this is driving me crazy!

**Pull request merged**
